import {useEffect,useRef,useState} from "react";
import {retainHumanCreateIntent,finishHumanCreateIntent,humanCreateIdentity} from "./create-intent";
import {z} from "zod";
import {HumanEvidenceSchema,HumanFormSchema,type HumanReviewCommand,type HumanReviewView,type ReviewReleaseSchema,type HumanReviewTransportRequest} from "@openpond/evals/human-review";
import {humanRequest,humanApi,type HumanInboxContext} from "./api";
import {MemberPicker} from "./MemberPicker";
import {WorkspacePanel,useWorkspaceActions} from "../labs/workspace/WorkspacePanel";
export type NativeHumanReviewSelection={executionId:string;receiptId:string};
export function HumanReviewLaunch({context,projectId,selections,graders,onOpenReview,tasks}:{context:HumanInboxContext;projectId:string;selections:NativeHumanReviewSelection[];graders:{id:string;name:string}[];onOpenReview:(record:HumanReviewView)=>void;tasks?:{dataset:z.infer<typeof ReviewReleaseSchema>;taskIds?:string[];all?:true;kind:"author"|"execute"}}){
  const [open,setOpen]=useState(false),[grader,setGrader]=useState(graders[0]?.id??""),[delegate,setDelegate]=useState(false),[dueAt,setDueAt]=useState(""),[assignee,setAssignee]=useState(""),[approval,setApproval]=useState(false),[manager,setManager]=useState(""),[distinct,setDistinct]=useState(false),[blind,setBlind]=useState(false),[minimumRaters,setMinimumRaters]=useState(1),[reviewer,setReviewer]=useState(""),[reviewers,setReviewers]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const pendingSnapshot=useRef<HumanReviewTransportRequest|null>(null),pending=useRef<HumanReviewCommand[]>([]),scope=useRef(context.scope);useWorkspaceActions(open?[{id:"human-review-create",label:"New assignment",onSelect:()=>setOpen(true)}]:[]);
  const retained=useRef<ReturnType<typeof retainHumanCreateIntent>|null>(null),contextKey=`${context.scope}:${context.actorId}:${context.location}`,currentKey=useRef(contextKey);currentKey.current=contextKey;
  const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
  async function start(){const key=contextKey;setBusy(true);setError(null);try{if(scope.current!==context.scope)throw new Error("Workspace changed. Reopen this review.");if(!pending.current.length){retained.current??=retainHumanCreateIntent({scope:context.scope,actorId:context.actorId,location:context.location},{projectId,grader,tasks:tasks??null,selections,delegate,assignee,approval,manager,distinct,minimumRaters,reviewers,blind,dueAt});pendingSnapshot.current??=tasks?{endpoint:"snapshot_tasks",scope:context.scope,projectId,graderId:grader,dataset:tasks.dataset,...(tasks.all?{all:true as const}:{taskIds:tasks.taskIds})}:delegate?{endpoint:context.location==="local"?"share_local":"publish_evidence",scope:context.scope,projectId,graderId:grader,selections,operationId:`publish-${retained.current.seed}`,audience:[assignee,manager,...reviewers].filter(Boolean),workspaceVisible:!assignee}:{endpoint:"snapshot",scope:context.scope,projectId,graderId:grader,selections};const snapshot=z.object({evidence:HumanEvidenceSchema,form:HumanFormSchema}).strict().parse(await humanRequest(context,pendingSnapshot.current!));const individual=tasks?snapshot.evidence.taskIds!.map(id=>({...snapshot.evidence,taskIds:[id]})):[snapshot.evidence];pending.current=individual.map(evidence=>({action:"create",operationId:`create-${humanCreateIdentity(retained.current!.seed,evidence.taskIds?.[0]??"grade")}`,id:humanCreateIdentity(retained.current!.seed,evidence.taskIds?.[0]??"grade"),expectedRevision:0,projectId,...(dueAt?{dueAt:new Date(dueAt).toISOString()}:{}),kind:tasks?.kind??"grade",title:tasks?`${tasks.kind==="execute"?"Perform":"Author"} task ${evidence.taskIds![0]}`:selections.length===2?"Assess A/B attempts":"Assess attempt",evidence,form:snapshot.form,assigneeId:delegate?assignee||null:null,policy:{approval:approval?"manager":"none",minimumRaters:approval?minimumRaters:1,managerIds:approval&&manager?[manager]:[],reviewerIds:reviewers,queueClaim:delegate&&!assignee,teamVisible:delegate,distinctManager:approval&&distinct,independentRaters:true,blindPair:blind}}));}if(!active.current||currentKey.current!==key)return;let last:HumanReviewView|undefined;while(pending.current.length&&active.current&&currentKey.current===key){last=await humanApi.command(delegate&&context.location==="local"?{...context,location:"hosted"}:context,pending.current[0]!);pending.current.shift();}if(!active.current||currentKey.current!==key)return;pendingSnapshot.current=null;if(retained.current)finishHumanCreateIntent(retained.current);retained.current=null;setOpen(false);window.dispatchEvent(new Event("human-review-changed"));if(last)onOpenReview(last);}catch(e){if(active.current&&currentKey.current===key)setError(e instanceof Error?e.message:"Assignment creation failed.");}finally{if(active.current&&currentKey.current===key)setBusy(false);}}
  return <><button type="button" disabled={!projectId||!graders.length||(!tasks&&!selections.length)} onClick={()=>setOpen(true)}>{tasks?tasks.kind==="author"?"Assign authoring":"Assign execution":"Human review"}</button>{open?<WorkspacePanel action="human-review-create" label="Human review" onRequestClose={()=>setOpen(false)}><h2>{tasks?"Assign selected tasks":"Review retained attempts"}</h2><fieldset disabled={busy||Boolean(pendingSnapshot.current)}><label>Human grader<select value={grader} disabled={busy||!!pending.current.length} onChange={e=>setGrader(e.target.value)}>{graders.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><p>Opening and saving an assessment starts no model or training job.</p><label><input type="checkbox" disabled={Boolean(tasks)&&context.location==="local"} checked={delegate} onChange={e=>setDelegate(e.target.checked)}/>Delegate this work (publish policy-facing evidence to the selected team reviewers)</label><label>Due date (optional)<input type="datetime-local" value={dueAt} onChange={event=>setDueAt(event.target.value)}/></label>{delegate?<MemberPicker context={context.location==="local"?{...context,location:"hosted"}:context} value={assignee} onChange={setAssignee}/>:null}<label><input type="checkbox" checked={approval} onChange={e=>setApproval(e.target.checked)}/>Require manager acceptance</label>{approval?<><MemberPicker context={delegate&&context.location==="local"?{...context,location:"hosted"}:context} value={manager} onChange={setManager} label="Manager"/><label><input type="checkbox" checked={distinct} onChange={e=>setDistinct(e.target.checked)}/>Require different manager</label><label>Independent raters<input type="number" value={minimumRaters} min={1} max={100} onChange={e=>setMinimumRaters(Number(e.target.value))}/></label><MemberPicker context={delegate&&context.location==="local"?{...context,location:"hosted"}:context} value={reviewer} onChange={setReviewer} label="Add reviewer"/><button type="button" onClick={()=>{if(reviewer&&!reviewers.includes(reviewer))setReviewers([...reviewers,reviewer]);setReviewer("");}}>Add reviewer</button>{reviewers.map(id=><p key={id}>{id}<button type="button" onClick={()=>setReviewers(reviewers.filter(r=>r!==id))}>Remove reviewer</button></p>)}</>:null}{selections.length===2?<label><input type="checkbox" checked={blind} onChange={e=>setBlind(e.target.checked)}/>Hide target identities from reviewers</label>:null}</fieldset>{error?<p role="alert">{error}</p>:null}<button type="button" disabled={busy} onClick={()=>setOpen(false)}>Close</button><button type="button" disabled={busy||!grader||distinct&&(!manager||manager===assignee)||!Number.isInteger(minimumRaters)} onClick={()=>void start()}>{pending.current.length?"Resume same operation":tasks?"Create assignments":delegate?"Create assignment":"Open review"}</button></WorkspacePanel>:null}</>;
}
