import "./human-forms.css";
import {HumanCriterionAnchors} from "./HumanCriterionAnchors";
import { useState } from "react";
import { HumanFormSchema, type HumanForm, type HumanAnswer } from "@openpond/evals/human-review";
import { NativeHumanAssessmentForm } from "./HumanAssessmentForm";
const initial = (rubric: string): HumanForm => ({ schemaVersion: "openpond.humanForm.v1", mode: "individual", instructions: rubric, criteria: [{ id: "quality", label: "Quality", instructions: "", required: true, allowAbstain: true, kind: "score", minimum: 0, maximum: 1, step: 0.1 }] });
export function NativeHumanFormEditor({ value, rubric, onChange }: { value: string; rubric: string; onChange: (value: string) => void }) {
  const original = value ? HumanFormSchema.safeParse((() => { try { return JSON.parse(value); } catch { return null; } })()) : { success: true as const, data: initial(rubric) };
  const [invalidOriginal,setInvalidOriginal]=useState(!original.success);
  const [preview, setPreview] = useState(false);
  const [answers, setAnswers] = useState<HumanAnswer[]>([]);
  const [form, setForm] = useState<HumanForm>(() => original.success ? original.data : initial(rubric));
  const validation = HumanFormSchema.safeParse(form);
  function update(next: HumanForm) { setInvalidOriginal(false);setForm(next); onChange(JSON.stringify(next)); setAnswers([]); }
  function criterion(index: number, patch: object) { update({ ...form, criteria: form.criteria.map((c, i) => i === index ? { ...c, ...patch } : c) } as HumanForm); }
  return <section className="human-form-editor" aria-label="Human assessment form">{invalidOriginal?<p role="alert" className="text-sm text-destructive">The stored form is invalid. The editor shows a starting form; explicitly save a corrected form before publication.</p>:null}<div className="flex justify-between"><h3 className="font-medium">Assessment form</h3><button type="button" className="training-button secondary" onClick={() => setPreview(p => !p)}>{preview ? "Edit form" : "Preview form"}</button></div>{!validation.success ? <p role="alert" className="text-sm text-destructive">{validation.error.issues[0]?.message}</p> : null}{preview && validation.success ? <NativeHumanAssessmentForm form={form} answers={answers} onChange={setAnswers} /> : <>
    <label className="block text-sm">Form instructions<textarea className="w-full rounded-md bg-muted p-2" value={form.instructions} maxLength={20000} onChange={e=>update({...form,instructions:e.target.value})}/></label>
    <label className="block text-sm">Assessment<select className="ml-2 rounded-md bg-muted p-2" value={form.mode} onChange={e => update({ ...form, mode: e.target.value as HumanForm["mode"], criteria: e.target.value === "pairwise" ? form.criteria : form.criteria.map(c => c.kind === "preference" ? { id: c.id, label: c.label, instructions: c.instructions, required: c.required, allowAbstain: c.allowAbstain, requireRationale: c.requireRationale, kind: "score" as const, minimum: 0, maximum: 5, step: 1 } : c) })}><option value="individual">Individual attempt</option><option value="pairwise">A/B pair</option></select></label>
    {form.criteria.map((c,i) => <div key={c.id} className="space-y-2 border-b border-border py-3"><div className="flex items-center gap-2"><input className="min-w-0 flex-1 rounded-md bg-muted p-2" aria-label="Criterion name" value={c.label} maxLength={500} onChange={e => criterion(i, { label: e.target.value })} /><select className="rounded-md bg-muted p-2" aria-label="Criterion type" value={c.kind} onChange={e => {
      const base = { id: c.id, label: c.label, instructions: c.instructions, required: c.required, allowAbstain: c.allowAbstain, requireRationale: c.requireRationale };
      const kind = e.target.value;
      const next = kind === "score" ? { ...base, kind, minimum: 0, maximum: 5, step: 1 } : kind === "category" ? { ...base, kind, options: ["Pass", "Fail"] } : kind === "text" ? { ...base, kind, minimumLength: 0, maximumLength: 2000 } : kind === "preference" ? { ...base, kind, allowTie: true, requireStrength: true } : { ...base, kind };
      update({ ...form, criteria: form.criteria.map((v,index) => index === i ? next : v) } as HumanForm);
    }}><option value="score">Score</option><option value="boolean">Yes / No</option><option value="category">Category</option><option value="text">Text</option>{form.mode === "pairwise" ? <option value="preference">Preference</option> : null}</select><button type="button" className="training-button secondary" disabled={form.criteria.length === 1} onClick={() => update({ ...form, criteria: form.criteria.filter((_,index) => index !== i) })}>Remove</button></div>
      <textarea aria-label="Criterion instructions" className="w-full rounded-md bg-muted p-2" value={c.instructions} maxLength={20000} onChange={e => criterion(i, { instructions: e.target.value })} />
      {c.kind === "score" ? <div className="flex gap-2">{(["minimum","maximum","step"] as const).map(key => <label key={key} className="text-sm">{key}<input className="ml-2 w-20 rounded-md bg-muted p-2" type="number" value={c[key]} onChange={e => criterion(i, { [key]: Number(e.target.value) })} /></label>)}</div> : null}
      {c.kind === "category" ? <label className="block text-sm">Options, one per line<textarea className="w-full rounded-md bg-muted p-2" value={c.options.join("\n")} onChange={e => criterion(i, { options: e.target.value.split("\n") })} /></label> : null}
      {c.kind === "text" ? <div className="flex gap-2"><label>Minimum length<input type="number" min={0} className="ml-2 w-20 rounded-md bg-muted p-2" value={c.minimumLength ?? 0} onChange={e => criterion(i, { minimumLength: Number(e.target.value) })} /></label><label>Maximum length<input type="number" className="ml-2 w-20 rounded-md bg-muted p-2" value={c.maximumLength} onChange={e => criterion(i, { maximumLength: Number(e.target.value) })} /></label></div> : null}
      <HumanCriterionAnchors criterion={c} onChange={anchors=>criterion(i,{anchors})}/>
      <div className="flex flex-wrap gap-4 text-sm">{(["required", "allowAbstain", "requireRationale"] as const).map(key => <label key={key} className="flex gap-2"><input type="checkbox" checked={Boolean(c[key])} onChange={e => criterion(i,{ [key]: e.target.checked })} />{key === "allowAbstain" ? "Allow abstention" : key === "requireRationale" ? "Require rationale" : "Required"}</label>)}{c.kind === "preference" ? <><label><input type="checkbox" checked={c.allowTie} onChange={e => criterion(i,{ allowTie: e.target.checked })} /> Allow tie</label><label><input type="checkbox" checked={c.requireStrength ?? false} onChange={e => criterion(i,{ requireStrength: e.target.checked })} /> Require strength</label></> : null}</div>
    </div>)}<button type="button" className="training-button secondary" disabled={form.criteria.length >= 100} onClick={() => update({ ...form, criteria: [...form.criteria, { id: `criterion-${crypto.randomUUID()}`, label: "New criterion", instructions: "", required: true, allowAbstain: true, kind: "score", minimum: 0, maximum: 5, step: 1 }] })}>Add criterion</button>
  </>}</section>;
}
