import {useEffect,useState} from "react";
import {z} from "zod";
import {ReviewReleaseSchema,type HumanReviewView} from "@openpond/evals/human-review";
import {humanRequest,type HumanInboxContext} from "./api";
const Result=z.object({result:ReviewReleaseSchema,evidence:z.unknown().optional()});
export function HumanExecutionControls({context,record,onConfigure,onResult,onOpenExecution}:{context:HumanInboxContext;record:HumanReviewView;onConfigure?:(record:HumanReviewView)=>void;onResult:(result:z.infer<typeof ReviewReleaseSchema>)=>void;onOpenExecution?:(id:string)=>void}){
  const [result,setResult]=useState<z.infer<typeof Result>|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const controller=new AbortController();setResult(null);setError(null);if(!record.execution?.executionId)return;void humanRequest(context,{endpoint:"execution",scope:context.scope,id:record.id,action:"result"},controller.signal).then(raw=>{if(controller.signal.aborted)return;const value=Result.parse(raw);if(value.result.id!==record.execution?.executionId)throw new Error("Execution result identity changed.");setResult(value);onResult(value.result);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[context.scope,context.actorId,context.location,context.connection,record.id,record.generation,record.execution?.executionId,refresh]);
  async function cancel(){setBusy(true);setError(null);try{await humanRequest(context,{endpoint:"execution",scope:context.scope,id:record.id,action:"cancel"});setRefresh(n=>n+1);}catch(e){setError(e instanceof Error?e.message:"Execution control failed.");}finally{setBusy(false);}}
  const evidence=result?.evidence as {cases?:{taskId:string;output:unknown;error:unknown}[];result?:{cases:{identity:{caseId:string};output:unknown;error:unknown}[]}}|undefined;
  return <section><h3>Task execution</h3>{record.execution?.executionId?<><p>Retained execution: {record.execution.executionId}</p>{onOpenExecution?<button type="button" onClick={()=>onOpenExecution(record.execution!.executionId!)}>Observe execution</button>:null}<button type="button" onClick={()=>setRefresh(n=>n+1)}>Read current result</button>{!result&&(record.permissions.reviewer||record.permissions.manager)?<button type="button" disabled={busy} onClick={()=>void cancel()}>Cancel execution</button>:null}{result?<><p>Sealed result ready for submission.</p>{(evidence?.cases??evidence?.result?.cases??[]).map((item,i)=><pre key={i}>{typeof item.output==="string"?item.output:JSON.stringify(item.output,null,2)}</pre>)}</>:null}</>:onConfigure?<button type="button" disabled={!record.permissions.reviewer} onClick={()=>onConfigure(record)}>Configure task execution</button>:<p>Configure the assigned tasks through Experiment setup.</p>}{error?<p role="status">{error}</p>:null}</section>;
}
