import {SubmissionHistory} from "./SubmissionHistory";
import {TaskPublicationControls} from "./TaskPublicationControls";
import {TaskProposalEditor} from "./TaskProposalEditor";
import {HumanExecutionControls} from "./HumanExecutionControls";
import {useEffect,useRef,useState} from "react";
import type {HumanAnswer,HumanInspection,HumanReviewCommand,HumanReviewView,HumanTaskProposal} from "@openpond/evals/human-review";
import {NativeHumanAssessmentForm} from "./HumanAssessmentForm";
import {useDraftNavigation} from "../labs/useDraftNavigation";
import {useWorkspacePanelControls} from "../labs/workspace/WorkspacePanel";
import {MemberPicker} from "./MemberPicker";
import {humanApi,type HumanInboxContext} from "./api";
export function HumanReviewInspector({context,record:initial,onChanged,onClose,onConfigureExecution,onOpenExecution}:{context:HumanInboxContext;record:HumanReviewView;onChanged:(record:HumanReviewView)=>void;onClose:()=>void;onConfigureExecution?:(record:HumanReviewView)=>void;onOpenExecution?:(id:string)=>void}){
  const [taskProposal,setTaskProposal]=useState<HumanTaskProposal|undefined>(initial.drafts.find(d=>d.actorId===context.actorId&&d.generation===initial.generation)?.taskProposal);
  const [executionResult,setExecutionResult]=useState<{id:string;revision:number;contentHash:string}|undefined>();
  const [record,setRecord]=useState(initial),[answers,setAnswers]=useState<HumanAnswer[]>(initial.drafts.find(d=>d.actorId===context.actorId&&d.generation===initial.generation)?.answers??[]),[note,setNote]=useState(initial.drafts.find(d=>d.actorId===context.actorId&&d.generation===initial.generation)?.note??""),[selectedProposalHash,setSelectedProposalHash]=useState(""),[reason,setReason]=useState(""),[assignee,setAssignee]=useState(initial.assigneeId??""),[inspection,setInspection]=useState<HumanInspection>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[conflict,setConflict]=useState(false);
  const [managerDirty,setManagerDirty]=useState(false);
  const dirty=useRef(false),pending=useRef<HumanReviewCommand|null>(null),contextKey=`${context.scope}:${context.actorId}:${context.location}`,activeKey=useRef(contextKey);activeKey.current=contextKey;
  useEffect(()=>{activeKey.current=contextKey;return()=>{activeKey.current="disposed";};},[contextKey]);
  function reload(){setRecord(initial);const draft=initial.drafts.find(d=>d.actorId===context.actorId&&d.generation===initial.generation);setAnswers(draft?.answers??[]);setTaskProposal(draft?.taskProposal);setNote(draft?.note??"");setAssignee(initial.assigneeId??"");dirty.current=false;setConflict(false);pending.current=null;}
  useEffect(()=>{setExecutionResult(undefined);},[initial.id,initial.generation,initial.execution?.executionId]);
  useEffect(()=>{if(initial.revision!==record.revision){if(dirty.current||pending.current)setConflict(true);else{setRecord(initial);setAssignee(initial.assigneeId??"");const draft=initial.drafts.find(d=>d.actorId===context.actorId&&d.generation===initial.generation);setAnswers(draft?.answers??[]);setNote(draft?.note??"");setTaskProposal(draft?.taskProposal);}}},[initial,record.revision]);
  useEffect(()=>{const controller=new AbortController();setInspection([]);void humanApi.inspect(context,initial.id,undefined,undefined,controller.signal).then(result=>{if(!controller.signal.aborted)setInspection(result);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[contextKey,context.connection,initial.id]);
  async function run(command:HumanReviewCommand){if(busy)return false;const key=contextKey;pending.current=command;setBusy(true);setError(null);try{const next=await humanApi.command(context,command);if(activeKey.current!==key)return false;pending.current=null;dirty.current=false;setManagerDirty(false);setRecord(next);setConflict(false);onChanged(next);window.dispatchEvent(new Event("human-review-changed"));return true;}catch(e){if(activeKey.current===key)setError(e instanceof Error?e.message:"Review operation failed.");return false;}finally{if(activeKey.current===key)setBusy(false);}}
  function mutate(payload:Record<string,unknown>){void run({...payload,id:record.id,expectedRevision:record.revision,operationId:crypto.randomUUID()} as HumanReviewCommand);}
  async function more(slot:number,cursor:string){try{const next=await humanApi.inspect(context,record.id,slot,cursor);setInspection(items=>items.map(item=>item.slotIndex===slot?{...next[0]!,events:[...item.events,...next[0]!.events]}:item));}catch(e){setError(e instanceof Error?e.message:"Evidence page failed.");}}
  const closed=["accepted","rejected","cancelled"].includes(record.status),submission=record.submissions.filter(s=>s.actorId===context.actorId&&s.generation===record.generation).at(-1),canWrite=record.permissions.reviewer&&!closed&&!conflict&&(!submission||record.status==="returned"),current=record.submissions.filter(s=>s.generation===record.generation&&!record.submissions.some(n=>n.supersedes===s.id));
  const navigation=useDraftNavigation({name:"Human review draft",dirty:dirty.current||managerDirty||Boolean(pending.current),busy,onLeave:onClose,
    ...(canWrite&&!managerDirty?{save:async()=>{if(conflict)return false;return run(pending.current??{action:"save_draft",id:record.id,expectedRevision:record.revision,operationId:crypto.randomUUID(),generation:record.generation,...(record.kind==="author"?{taskProposal}:{}),answers,note});}}:{})});
  const panel=useWorkspacePanelControls(),closeGuard=useRef(()=>{});
  closeGuard.current=()=>{void navigation.requestLeave(onClose);};
  useEffect(()=>{if(!panel?.active?.startsWith("human-review:"))return;return panel.registerClose(panel.active,()=>closeGuard.current());},[panel?.active,panel?.registerClose]);
  useEffect(()=>{if(!canWrite||!dirty.current||busy||pending.current||conflict)return;const timer=setTimeout(()=>mutate({action:"save_draft",generation:record.generation,...(record.kind==="author"?{taskProposal}:{}),answers,note}),900);return()=>clearTimeout(timer);},[answers,note,taskProposal,canWrite,busy,conflict,record.revision]);
  return <div className="evaluation-detail-body"><header><h2>{record.title}</h2><button type="button" onClick={()=>void navigation.requestLeave(onClose)}>Close</button></header><p>{record.status.replaceAll("_"," ")}</p>{record.dueAt?<p>Due {new Date(record.dueAt).toLocaleString()}</p>:null}{conflict?<p role="alert">This assignment changed during editing. <button type="button" onClick={reload}>Reload current draft</button></p>:null}{error?<p role="alert">{error}{pending.current?<button type="button" disabled={busy} onClick={()=>void run(pending.current!)}>Retry same operation</button>:null}</p>:null}
    {record.policy.blindPair?<p>Target labels are hidden. The retained answers or trace may still reveal identity; this is not guaranteed anonymous evidence.</p>:null}
    {inspection.map(item=><section key={item.slotIndex}><h3>{item.slot}</h3>{item.origin==="owner_attested_local"?<p>Owner-attested local evidence. This publication contains {item.coverage?.publishedEventCount} of {item.coverage?.sourceEventCount} policy-facing events and no artifacts. The original execution remains on its source computer.</p>:null}{item.evidenceLimited?<p>Assess observed behavior only; this attempt has limited evidence.</p>:null}<details><summary>Input</summary><pre>{typeof item.input==="string"?item.input:JSON.stringify(item.input,null,2)}</pre></details><pre>{typeof item.output==="string"?item.output:JSON.stringify(item.output,null,2)}</pre>{item.error?<p>{item.error}</p>:null}<details><summary>Observed events ({item.eventCount})</summary><pre>{JSON.stringify(item.events,null,2)}</pre>{item.nextEventCursor?<button type="button" onClick={()=>void more(item.slotIndex,item.nextEventCursor!)}>Load more events</button>:null}</details></section>)}
    {record.kind==="author"?<TaskProposalEditor context={context} record={record} value={canWrite?taskProposal:submission?.taskProposal??record.submissions.find(s=>s.taskProposal?.contentHash===record.decisions.at(-1)?.taskProposalHash)?.taskProposal} onChange={next=>{dirty.current=true;setTaskProposal(next);}} disabled={busy||!canWrite}/>:null}
    {record.kind==="execute"?<HumanExecutionControls context={context} record={record} onConfigure={onConfigureExecution} onOpenExecution={onOpenExecution} onResult={setExecutionResult}/>:null}
    {record.decisions.at(-1)?.outcome==="request_changes"?<p>Changes requested: {record.decisions.at(-1)?.note}</p>:null}
    <NativeHumanAssessmentForm form={record.form} answers={canWrite?answers:submission?.answers??record.decisions.at(-1)?.answers??[]} onChange={next=>{dirty.current=true;setAnswers(next);}} disabled={busy||!canWrite}/>
    {canWrite?<><label>Review note<textarea value={note} maxLength={20000} onChange={e=>{dirty.current=true;setNote(e.target.value);}}/></label><button type="button" disabled={busy} onClick={()=>mutate({action:"save_draft",generation:record.generation,...(record.kind==="author"?{taskProposal}:{}),answers,note})}>Save draft</button><button type="button" disabled={busy||record.kind==="execute"&&!executionResult||record.kind==="author"&&!taskProposal} onClick={()=>mutate({action:"submit",generation:record.generation,evidenceHash:record.evidenceHash,formHash:record.formHash,...(record.kind==="execute"?{executionResult}:{}),...(record.kind==="author"?{taskProposal}:{}),answers,note})}>{record.policy.approval==="none"?"Save review":"Submit review"}</button></>:null}
    {record.permissions.claim&&!closed?<button type="button" disabled={busy} onClick={()=>mutate({action:"claim"})}>Claim assignment</button>:null}
    {record.permissions.manager&&!closed?<details><summary>Assignment and decisions</summary><label>Reason<textarea value={reason} onChange={e=>{setManagerDirty(true);setReason(e.target.value);}} maxLength={20000}/></label>{record.status==="submitted"&&record.policy.approval==="manager"?<>{record.kind==="author"?<label>Accepted task proposal<select value={selectedProposalHash} onChange={e=>{setManagerDirty(true);setSelectedProposalHash(e.target.value);}}><option value="">Select a submitted proposal</option>{current.filter(s=>s.taskProposal).map(s=><option key={s.id} value={s.taskProposal!.contentHash}>{s.actorId}, {s.submittedAt}</option>)}</select></label>:null}<NativeHumanAssessmentForm form={record.form} answers={answers} onChange={next=>{setManagerDirty(true);setAnswers(next);}} disabled={busy}/>{(["accept","request_changes","reject"] as const).map(outcome=><button type="button" key={outcome} disabled={busy||!current.length||(outcome!=="accept"&&!reason.trim())} onClick={()=>mutate({action:"decide",outcome,submissions:current.map(s=>({id:s.id,contentHash:s.contentHash})),...(record.kind==="author"?{taskProposalHash:selectedProposalHash}:{}),answers,note:reason})}>{outcome.replaceAll("_"," ")}</button>)}</>:null}<MemberPicker context={context} value={assignee} onChange={next=>{setManagerDirty(true);setAssignee(next);}}/><button type="button" disabled={busy||!reason.trim()} onClick={()=>mutate({action:"reassign",assigneeId:assignee||null,note:reason})}>Reassign</button><button type="button" disabled={busy||!reason.trim()} onClick={()=>mutate({action:"cancel",note:reason})}>Cancel assignment</button></details>:null}
    <TaskPublicationControls context={context} record={record} onChanged={next=>{setRecord(next);onChanged(next);}}/>
    <SubmissionHistory record={record}/>{navigation.dialog}
  </div>;
}
