import {useEffect,useState} from "react";
import {z} from "zod";
import type {RunExperiment} from "openpond-sdk/experiments";
import type {WorkspaceApi} from "../labs/workspace/workspace-api";
const Choices=z.array(z.object({id:z.string(),name:z.string(),providerId:z.literal("custom-openai-compatible"),configurationHash:z.string().regex(/^[a-f0-9]{64}$/),contextWindow:z.number().int().positive(),outputLimit:z.number().int().positive()}).strict());
export function LocalInferenceChoice({api,policy,onChange}:{api:WorkspaceApi;policy:RunExperiment["request"]["policy"];onChange:(policy:RunExperiment["request"]["policy"])=>void}){
  const [choices,setChoices]=useState<z.infer<typeof Choices>>([]),[error,setError]=useState<string|null>(null),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const controller=new AbortController();setChoices([]);setError(null);void api.local("localInferenceChoices",{},controller.signal).then(raw=>{if(!controller.signal.aborted)setChoices(Choices.parse(raw));}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[api.key,refresh]);
  const local=policy.kind==="hosted_chat"&&policy.localRuntime?.providerId==="custom-openai-compatible"?policy.localRuntime:undefined;
  return <section><h3>Local inference</h3><p>Select the configured loopback OpenAI-compatible endpoint. Reported tokens are retained; monetary cost remains unknown. Starting reserves your request allocation and sends no target request to OpenPond.</p>{error?<p role="alert">{error}</p>:null}<label>Local model<select value={local&&policy.kind==="hosted_chat"?policy.modelId:""} onChange={e=>{const choice=choices.find(c=>c.id===e.target.value);if(!choice||policy.kind!=="hosted_chat")return;onChange({...policy,modelId:choice.id,localRuntime:{providerId:choice.providerId,configurationHash:choice.configurationHash,maximumRequestCostUsd:0.001,requestTimeoutMs:90000},maxOutputTokens:Math.min(policy.maxOutputTokens,choice.outputLimit),harness:undefined,candidate:undefined});}}><option value="">Select local model</option>{choices.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button type="button" onClick={()=>setRefresh(n=>n+1)}>Refresh choices</button>{!choices.length&&!error?<p>Configure the local provider in Settings and refresh its model catalog with context/output bounds before starting.</p>:null}{local&&policy.kind==="hosted_chat"?<><label>Request allocation ($, reserved while measured cost is unknown)<input type="number" min={0.000001} max={10000} step={0.000001} value={local.maximumRequestCostUsd} onChange={e=>onChange({...policy,localRuntime:{...local,maximumRequestCostUsd:Number(e.target.value)}})}/></label><label>Request timeout (seconds)<input type="number" min={1} max={300} value={local.requestTimeoutMs/1000} onChange={e=>onChange({...policy,localRuntime:{...local,requestTimeoutMs:Number(e.target.value)*1000}})}/></label><button type="button" onClick={()=>{const{localRuntime,...hosted}=policy;void localRuntime;onChange(hosted);}}>Use hosted model configuration</button></>:null}</section>;
}
