import {useEffect,useRef,useState} from "react";
import {z} from "zod";
import {HumanTaskPatchSchema,ReviewReleaseSchema,sealHumanTaskProposal,type HumanTaskProposal,type HumanReviewView} from "@openpond/evals/human-review";
import {humanRequest,type HumanInboxContext} from "./api";
const Baseline=z.object({dataset:ReviewReleaseSchema,tasks:z.array(HumanTaskPatchSchema)}).strict();
export function TaskProposalEditor({context,record,value,onChange,disabled}:{context:HumanInboxContext;record:HumanReviewView;value:HumanTaskProposal|undefined;onChange:(value:HumanTaskProposal)=>void;disabled:boolean}){
  const currentValue=useRef(value);currentValue.current=value;
  const [includeReference,setIncludeReference]=useState(false);
  const [baseline,setBaseline]=useState<z.infer<typeof Baseline>|null>(null),[error,setError]=useState<string|null>(null);
  useEffect(()=>{const controller=new AbortController();setError(null);setBaseline(null);void humanRequest(context,{endpoint:"author_tasks",scope:context.scope,id:record.id,...(includeReference?{includeReference:true as const}:{})},controller.signal).then(raw=>{if(controller.signal.aborted)return;const result=Baseline.parse(raw);if(!record.evidence||result.dataset.contentHash!==record.evidence.dataset.contentHash)throw new Error("Task proposal baseline changed.");setBaseline(result);if(includeReference)onChange(sealHumanTaskProposal((currentValue.current?.tasks??result.tasks).map(task=>({...task,expectedOutput:result.tasks.find(t=>t.taskId===task.taskId)?.expectedOutput??null}))));}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[context.scope,context.actorId,context.location,context.connection,record.id,record.generation,includeReference]);
  const tasks=value?.tasks??baseline?.tasks;
  function change(index:number,patch:object){if(!tasks)return;onChange(sealHumanTaskProposal(tasks.map((task,i)=>i===index?{...task,...patch}:task)));}
  return <section><h3>Task proposal</h3><p>Edits remain a proposal until accepted and explicitly published by the Dataset owner. Source family, split, private references and grader bindings remain pinned.</p>{record.permissions.owner&&!disabled?<label><input type="checkbox" checked={includeReference} onChange={e=>setIncludeReference(e.target.checked)}/>Load reference output for owner editing</label>:null}{value&&"referenceRedacted" in value?<p>Protected reference outputs are omitted from this proposal view.</p>:null}{error?<p role="alert">{error}</p>:null}{tasks?tasks.map((task,index)=><fieldset key={task.taskId} disabled={disabled}><legend>{task.taskId}</legend><TaskValueField label="Task input" value={task.input} onChange={input=>change(index,{input})}/><TaskValueField label="Policy-visible context" value={task.policyVisibleContext} onChange={policyVisibleContext=>change(index,{policyVisibleContext})}/>{task.expectedOutput!==undefined?<><label><input type="checkbox" checked={task.expectedOutput!==null} onChange={e=>change(index,{expectedOutput:e.target.checked?{}:null})}/>Reference output for this task</label>{task.expectedOutput!==null?<TaskValueField label="Reference output" value={task.expectedOutput} onChange={expectedOutput=>change(index,{expectedOutput})}/>:null}</>:null}</fieldset>):<p role="status">Loading authorized task baseline…</p>}{baseline&&!value&&!disabled?<button type="button" onClick={()=>onChange(sealHumanTaskProposal(baseline.tasks))}>Keep baseline as proposal</button>:null}</section>;
}
export function TaskValueField({label,value,onChange,depth=0}:{label:string;value:unknown;onChange:(value:unknown)=>void;depth?:number}){
  const [newKey,setNewKey]=useState("");
  if(depth>12)return <p>Nested value exceeds editor depth. Preserve it or revise through the Dataset editor.</p>;
  if(Array.isArray(value))return <fieldset><legend>{label}</legend>{value.map((item,index)=><div key={index}><TaskValueField label={String(index+1)} value={item} depth={depth+1} onChange={next=>onChange(value.map((current,i)=>i===index?next:current))}/><button type="button" onClick={()=>onChange(value.filter((_,i)=>i!==index))}>Remove item</button></div>)}<button type="button" onClick={()=>onChange([...value,""])}>Add item</button></fieldset>;
  if(value&&typeof value==="object"){const entries=value as Record<string,unknown>;return <fieldset><legend>{label}</legend>{Object.entries(entries).map(([key,item])=><div key={key}><TaskValueField label={key} value={item} depth={depth+1} onChange={next=>onChange({...entries,[key]:next})}/><button type="button" onClick={()=>{const next={...entries};delete next[key];onChange(next);}}>Remove field</button></div>)}<label>New field<input value={newKey} maxLength={240} onChange={e=>setNewKey(e.target.value)}/></label><button type="button" disabled={!newKey.trim()||Object.hasOwn(entries,newKey)} onClick={()=>{onChange({...entries,[newKey]:""});setNewKey("");}}>Add field</button></fieldset>;}
  const kind=value===null?"null":typeof value;return <div><label>{label}<select aria-label={`${label} type`} value={kind} onChange={e=>onChange(e.target.value==="string"?"":e.target.value==="number"?0:e.target.value==="boolean"?false:e.target.value==="array"?[]:e.target.value==="object"?{}:null)}>{["string","number","boolean","null","object","array"].map(type=><option key={type}>{type}</option>)}</select>{kind==="boolean"?<input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>:kind==="number"?<input type="number" value={String(value)} onChange={e=>onChange(Number(e.target.value))}/>:kind==="string"?<textarea value={String(value)} maxLength={20000} onChange={e=>onChange(e.target.value)}/>:null}</label></div>;
}
