import type { HttpRouteModule } from "../http-route-types.js";
import { handleCoreRoutes } from "./core-routes.js";
import { handleCreateImproveRoutes } from "./create-improve-routes.js";
import { handleCommunityRoutes } from "./community-routes.js";
import { handleChatWorkflowRoutes } from "./chat-workflow-routes.js";
import { handleDesktopBrowserRoutes } from "./desktop-browser-routes.js";
import { handleEventRoutes } from "./event-routes.js";
import { handleExtensionRoutes } from "./extension-routes.js";
import { handleHarnessRoutes } from "./harness-routes.js";
import { handleRefinerRoutes } from "./refiner-routes.js";
import { handleLocalAgentScheduleRoutes } from "./local-agent-schedule-routes.js";
import { handleOrganizationRoutes } from "./organization-routes.js";
import { handleProjectCloudRoutes } from "./project-cloud-routes.js";
import { handleSandboxRoutes } from "./sandbox-routes.js";
import { handleSavedWorkRoutes } from "./saved-work-routes.js";
import { handleSessionRoutes } from "./session-routes.js";
import { handleSettingsRoutes } from "./settings-routes.js";
import { handleUsageRoutes } from "./usage-routes.js";
import { handleTeamChatRoutes } from "./team-chat-routes.js";
import { handleTrainingRoutes } from "./training-routes.js";
import { handleWorkspaceRoutes } from "./workspace-routes.js";
import { handleWorkOutputRoutes } from "./work-output-routes.js";
import { handleWorkEvidenceRoutes } from "./work-evidence-routes.js";

export const AUTHENTICATED_ROUTE_TABLE: HttpRouteModule[] = [
  { id: "events", handle: handleEventRoutes },
  { id: "work-outputs", handle: handleWorkOutputRoutes },
  { id: "work-evidence", handle: handleWorkEvidenceRoutes },
  { id: "extensions", handle: handleExtensionRoutes },
  { id: "harness", handle: handleHarnessRoutes },
  { id: "refiner", handle: handleRefinerRoutes },
  { id: "training", handle: handleTrainingRoutes },
  { id: "create-improve", handle: handleCreateImproveRoutes },
  { id: "communities", handle: handleCommunityRoutes },
  { id: "chat-workflows", handle: handleChatWorkflowRoutes },
  { id: "local-agent-schedules", handle: handleLocalAgentScheduleRoutes },
  { id: "saved-work", handle: handleSavedWorkRoutes },
  { id: "usage", handle: handleUsageRoutes },
  { id: "core", handle: handleCoreRoutes },
  { id: "desktop-browser", handle: handleDesktopBrowserRoutes },
  { id: "organizations", handle: handleOrganizationRoutes },
  { id: "sandbox", handle: handleSandboxRoutes },
  { id: "projects-cloud", handle: handleProjectCloudRoutes },
  { id: "team-chat", handle: handleTeamChatRoutes },
  { id: "settings-providers", handle: handleSettingsRoutes },
  { id: "workspace", handle: handleWorkspaceRoutes },
  { id: "sessions", handle: handleSessionRoutes },
];
