import type {
  Approval,
  BootstrapPayload,
  CloudWorkItem,
  CloudWorkItemDetail,
  CloudWorkItemMessage,
  CloudWorkItemBackgroundRequest,
  CloudProject,
  CompactSessionRequest,
  CreateCloudWorkItemRequest,
  CreateLocalProjectRequest,
  CreateSessionRequest,
  LocalProject,
  UpdateLocalProjectAgentSetupRequest,
  PatchSessionRequest,
  PatchSidebarAppPreferenceRequest,
  ReorderSidebarAppsRequest,
  ResolveApprovalRequest,
  RemoteAccessStatus,
  RemoteAccessToggleResponse,
  RuntimeEvent,
  SaveWorkspaceFileRequest,
  SaveOpenPondAccountRequest,
  SendTurnRequest,
  Session,
  SidebarAppPreference,
  SidebarAppPreferences,
  SwitchOpenPondAccountRequest,
  ListCloudWorkItemsRequest,
  OpenCloudWorkItemRequest,
  SendCloudWorkItemMessageRequest,
  UploadLocalProjectCloudSourceRequest,
  Turn,
  UpdateAppPreferencesRequest,
  UpdatePersonalizationRequest,
  UpdateProviderSettingsRequest,
  WorkspaceBranchRequest,
  WorkspaceDiffFile,
  WorkspaceDiffSummary,
  WorkspaceLspActionRequest,
  WorkspaceLspActionResponse,
  WorkspaceLspDiagnosticsResponse,
  WorkspaceLspSettingsStatusResponse,
  WorkspaceLspTouchRequest,
  WorkspaceState,
  WorkspaceTemplateConfigView,
  WorkspaceToolRequest,
  WorkspaceToolResult,
} from "@openpond/contracts";
import type {
  CreateOpenPondOrganizationRequest,
  GenerateOpenPondOrganizationMcpServerRequest,
  OpenPondOrganizationMemberResponse,
  OpenPondOrganizationMembersResponse,
  OpenPondOrganizationMcpServerResponse,
  OpenPondOrganizationResponse,
  OpenPondOrganizationsResponse,
  UpdateOpenPondOrganizationRequest,
  UpsertOpenPondOrganizationMemberRequest,
} from "../../lib/organization-types";
import type {
  SandboxRuntimeCreateInput,
  SandboxRuntimeResponse,
  SandboxRuntimeSandboxResponse,
  SandboxAgentRunInput,
  SandboxAgentRunResponse,
  SandboxAgentListResponse,
  SandboxAgentResponse,
  SandboxAgentUpsertInput,
  CreateSandboxRequest,
  ForkSandboxRequest,
  ForkSandboxSnapshotRequest,
  LaunchSandboxTemplateRequest,
  SandboxBillingStatusResponse,
  SandboxExecResponse,
  SandboxFileDeleteResponse,
  SandboxFileDownloadResponse,
  SandboxFileListResponse,
  SandboxFileMkdirResponse,
  SandboxFileMoveResponse,
  SandboxFileSearchResponse,
  SandboxFileStatResponse,
  SandboxFileUploadResponse,
  SandboxForkResponse,
  SandboxGitBranchResponse,
  SandboxGitCommitResponse,
  SandboxGitDiffResponse,
  SandboxGitPullResponse,
  SandboxGitPushResponse,
  SandboxGitStatusResponse,
  SandboxIntegrationConnectionLeaseInput,
  SandboxIntegrationConnectionsResponse,
  SandboxIntegrationConnectionStatusFilter,
  SandboxIntegrationLeasesResponse,
  SandboxListResponse,
  SandboxLogsResponse,
  SandboxOpenPortResponse,
  SandboxPreviewAuthPolicyInput,
  SandboxProjectListResponse,
  SandboxProjectResponse,
  SandboxProjectSourceUploadInput,
  SandboxProjectUpsertInput,
  SandboxProcessListResponse,
  SandboxProcessStartResponse,
  SandboxProcessStatusResponse,
  SandboxProcessStopResponse,
  SandboxPtyInputResponse,
  SandboxPtyListResponse,
  SandboxPtyStartResponse,
  SandboxPtyStatusResponse,
  SandboxPtyStopResponse,
  SandboxReceiptResponse,
  SandboxReceiptsResponse,
  SandboxRecordResponse,
  SandboxReplayArtifactsResponse,
  SandboxReplayInput,
  SandboxReplayListResponse,
  SandboxReplayLogsResponse,
  SandboxReplayResponse,
  SandboxSecretListResponse,
  SandboxSecretResponse,
  SandboxSnapshotCatalogResponse,
  SandboxSnapshotResponse,
  SandboxSnapshotValidateInput,
  SandboxSnapshotValidationResponse,
  SandboxSnapshotUpdateInput,
  SandboxTemplateBuildCreateInput,
  SandboxTemplateBuildListResponse,
  SandboxTemplateBuildLogsResponse,
  SandboxTemplateBuildResponse,
  SandboxTemplateCatalogResponse,
  SandboxTemplateLaunchResponse,
  SandboxVolumeCreateInput,
  SandboxVolumeListResponse,
  SandboxVolumeResponse,
} from "../../lib/sandbox-types";
import {
  apiFetch,
  base64ToText,
  sandboxScopeQuery,
  textToBase64,
  type ClientConnection,
  type SandboxScopeInput,
} from "../api-client";

export const sandboxGitApi = {
  sandboxGitStatus: (connection: ClientConnection, sandboxId: string) =>
    apiFetch<SandboxGitStatusResponse>(
      connection,
      `/v1/sandboxes/${encodeURIComponent(sandboxId)}/git/status`,
    ),
  sandboxGitDiff: (connection: ClientConnection, sandboxId: string, input: { baseRef?: string }) =>
    apiFetch<SandboxGitDiffResponse>(
      connection,
      `/v1/sandboxes/${encodeURIComponent(sandboxId)}/git/diff`,
      {
        method: "POST",
        body: JSON.stringify(input),
      },
    ),
  sandboxGitBranch: (
    connection: ClientConnection,
    sandboxId: string,
    input: { branch: string; create?: boolean; startPoint?: string },
  ) =>
    apiFetch<SandboxGitBranchResponse>(
      connection,
      `/v1/sandboxes/${encodeURIComponent(sandboxId)}/git/branch`,
      {
        method: "POST",
        body: JSON.stringify(input),
      },
    ),
  sandboxGitCommit: (
    connection: ClientConnection,
    sandboxId: string,
    input: { message: string; paths?: string[]; all?: boolean },
  ) =>
    apiFetch<SandboxGitCommitResponse>(
      connection,
      `/v1/sandboxes/${encodeURIComponent(sandboxId)}/git/commit`,
      {
        method: "POST",
        body: JSON.stringify(input),
      },
    ),
  sandboxGitPull: (
    connection: ClientConnection,
    sandboxId: string,
    input: { remote?: string; branch?: string; rebase?: boolean; ffOnly?: boolean },
  ) =>
    apiFetch<SandboxGitPullResponse>(
      connection,
      `/v1/sandboxes/${encodeURIComponent(sandboxId)}/git/pull`,
      {
        method: "POST",
        body: JSON.stringify(input),
      },
    ),
  sandboxGitPush: (
    connection: ClientConnection,
    sandboxId: string,
    input: {
      remote?: string;
      branch?: string;
      setUpstream?: boolean;
      forceWithLease?: boolean;
    },
  ) =>
    apiFetch<SandboxGitPushResponse>(
      connection,
      `/v1/sandboxes/${encodeURIComponent(sandboxId)}/git/push`,
      {
        method: "POST",
        body: JSON.stringify(input),
      },
    ),
};
