import type { ReactNode } from "react";
import "../../styles/workspace/git-dialogs.css";
import { CloudUpload, GitBranch, GitCommitHorizontal, Github, Upload, X } from "../icons";

export type CommitNextStep = "commit" | "commit_push" | "commit_publish" | "commit_pr";

type CommitDialogProps = {
  open: boolean;
  branch: string | null;
  filesChanged: number;
  additions: number;
  deletions: number;
  message: string;
  includeUnstaged: boolean;
  nextStep: CommitNextStep;
  draft: boolean;
  busy: boolean;
  canPush: boolean;
  canPublish: boolean;
  onMessageChange: (value: string) => void;
  onIncludeUnstagedChange: (value: boolean) => void;
  onNextStepChange: (value: CommitNextStep) => void;
  onDraftChange: (value: boolean) => void;
  onClose: () => void;
  onSubmit: () => void;
};

type BranchDialogProps = {
  open: boolean;
  branchName: string;
  busy: boolean;
  onBranchNameChange: (value: string) => void;
  onSetPrefix: () => void;
  onClose: () => void;
  onSubmit: () => void;
};

export function CommitDialog({
  open,
  branch,
  filesChanged,
  additions,
  deletions,
  message,
  includeUnstaged,
  nextStep,
  draft,
  busy,
  canPush,
  canPublish,
  onMessageChange,
  onIncludeUnstagedChange,
  onNextStepChange,
  onDraftChange,
  onClose,
  onSubmit,
}: CommitDialogProps) {
  if (!open) return null;
  return (
    <div className="git-dialog-backdrop" role="presentation">
      <form
        className="git-dialog commit-dialog"
        aria-label="Commit changes"
        onSubmit={(event) => {
          event.preventDefault();
          onSubmit();
        }}
      >
        <DialogCloseButton disabled={busy} onClose={onClose} />
        <div className="git-dialog-icon">
          <GitCommitHorizontal size={18} />
        </div>
        <h2>Commit your changes</h2>
        <div className="git-dialog-row">
          <span>Branch</span>
          <strong>
            <GitBranch size={14} />
            {branch ?? "No branch"}
          </strong>
        </div>
        <div className="git-dialog-row">
          <span>Changes</span>
          <strong>
            {filesChanged} {filesChanged === 1 ? "file" : "files"}
            <span className="git-dialog-additions">+{additions}</span>
            <span className="git-dialog-deletions">-{deletions}</span>
          </strong>
        </div>
        <label className="git-dialog-toggle">
          <input
            checked={includeUnstaged}
            disabled={busy}
            type="checkbox"
            onChange={(event) => onIncludeUnstagedChange(event.target.checked)}
          />
          <span />
          Include unstaged
        </label>
        <label className="git-dialog-field">
          <span>
            Commit message
            <small>Leave blank to use an autogenerated message</small>
          </span>
          <textarea
            value={message}
            disabled={busy}
            placeholder="Update workspace"
            onChange={(event) => onMessageChange(event.target.value)}
          />
        </label>
        <fieldset className="git-dialog-next">
          <legend>Next steps</legend>
          <CommitStep
            active={nextStep === "commit"}
            icon={<GitCommitHorizontal size={14} />}
            label="Commit"
            disabled={busy}
            onSelect={() => onNextStepChange("commit")}
          />
          <CommitStep
            active={nextStep === "commit_push"}
            icon={<Upload size={14} />}
            label="Commit & push"
            disabled={busy || !canPush}
            onSelect={() => onNextStepChange("commit_push")}
          />
          {canPublish && (
            <CommitStep
              active={nextStep === "commit_publish"}
              icon={<CloudUpload size={14} />}
              label="Commit & publish"
              disabled={busy}
              onSelect={() => onNextStepChange("commit_publish")}
            />
          )}
          <CommitStep
            active={nextStep === "commit_pr"}
            icon={<Github size={14} />}
            label="Commit & create PR"
            disabled
            onSelect={() => onNextStepChange("commit_pr")}
          />
        </fieldset>
        <div className="git-dialog-footer">
          <label className="git-dialog-toggle draft-toggle">
            <input
              checked={draft}
              disabled={busy || nextStep !== "commit_pr"}
              type="checkbox"
              onChange={(event) => onDraftChange(event.target.checked)}
            />
            <span />
            Draft
          </label>
          <button className="git-dialog-primary" disabled={busy || filesChanged === 0} type="submit">
            Continue
          </button>
        </div>
      </form>
    </div>
  );
}

export function BranchDialog({
  open,
  branchName,
  busy,
  onBranchNameChange,
  onSetPrefix,
  onClose,
  onSubmit,
}: BranchDialogProps) {
  if (!open) return null;
  return (
    <div className="git-dialog-backdrop" role="presentation">
      <form
        className="git-dialog branch-dialog"
        aria-label="Create branch"
        onSubmit={(event) => {
          event.preventDefault();
          onSubmit();
        }}
      >
        <DialogCloseButton disabled={busy} onClose={onClose} />
        <div className="git-dialog-icon">
          <GitBranch size={18} />
        </div>
        <h2>Work here</h2>
        <p>Create a branch to commit changes, push, and create a PR from this worktree.</p>
        <label className="git-dialog-field">
          <span>
            Branch name
            <button className="git-dialog-inline-action" disabled={busy} type="button" onClick={onSetPrefix}>
              Set prefix
            </button>
          </span>
          <input
            autoFocus
            disabled={busy}
            value={branchName}
            onChange={(event) => onBranchNameChange(event.target.value)}
          />
        </label>
        <button className="git-dialog-primary full" disabled={busy || !branchName.trim()} type="submit">
          Create
        </button>
      </form>
    </div>
  );
}

function CommitStep({
  active,
  icon,
  label,
  disabled,
  onSelect,
}: {
  active: boolean;
  icon: ReactNode;
  label: string;
  disabled?: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      aria-pressed={active}
      className={active ? "active" : ""}
      disabled={disabled}
      type="button"
      onClick={onSelect}
    >
      {icon}
      <span>{label}</span>
      {active && <span className="git-dialog-check">✓</span>}
    </button>
  );
}

function DialogCloseButton({ disabled, onClose }: { disabled: boolean; onClose: () => void }) {
  return (
    <button className="git-dialog-close" disabled={disabled} type="button" onClick={onClose}>
      <X size={16} />
    </button>
  );
}
