import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import {expect,test} from "vitest";
import {contentHash} from "@openpond/harness";
import {createHumanReviewService,type HumanReviewRepository,type HumanReviewAuthority,type HumanReviewCommand,acceptedHumanEvidence,dispatchAssignedHumanExecution,sealHumanTaskProposal} from "@openpond/evals/human-review";
import {NodeSqliteConnection} from "../store/sqlite/sqlite-driver-node.js";
import {HUMAN_REVIEW_SQL,createHumanReviewTransaction} from "../store/store-human-review.js";
// Failure story: restart, concurrent claim and retries must retain one exact
// judgment without restoring revoked grants or exposing another rater's draft.
test("SQLite review lifecycle preserves exact evidence, concurrency and current authority across restart",async()=>{
  const home=await mkdtemp(path.join(tmpdir(),"human-review-")),filename=path.join(home,"proof.sqlite");let db=new NodeSqliteConnection(filename),queue=Promise.resolve();
  db.exec(HUMAN_REVIEW_SQL);db.exec("CREATE TABLE executions(id TEXT PRIMARY KEY, operation TEXT NOT NULL, configuration_hash TEXT NOT NULL, sealed INTEGER NOT NULL, result_hash TEXT NOT NULL)");db.exec("CREATE TABLE grants(actor TEXT PRIMARY KEY, enabled INTEGER NOT NULL)");for(const actor of ["owner","rater-a","rater-b","manager"])db.run("INSERT INTO grants VALUES(?,1)",[actor]);
  const form={schemaVersion:"openpond.humanForm.v1" as const,mode:"individual" as const,instructions:"Assess observed quality",criteria:[{id:"quality",label:"Quality",instructions:"Use observed output",kind:"score" as const,minimum:0,maximum:5,step:1,required:true,allowAbstain:true,requireRationale:true}]};
  const release={id:"dataset",revision:1,contentHash:contentHash("dataset")},evidence={dataset:release,grader:{...release,id:"grader"},graderBinding:{id:"human",version:"1",contentHash:contentHash("compiled")},rubric:{...release,id:"rubric"},attempts:[{experimentId:"experiment",attemptId:"attempt",taskId:"task",targetId:"target",output:{...release,id:"output"},trace:null,familyKey:"family",split:"test" as const}]};
  const authority:HumanReviewAuthority={async member(c){if(!db.get<{enabled:number}>("SELECT enabled FROM grants WHERE actor=?",[c.actorId])?.enabled)throw new Error("revoked");},async owner(c){return c.actorId==="owner";},async evidence(_c,r){if(contentHash(r.evidence)!==contentHash(r.evidence.attempts.length?evidence:{...evidence,attempts:[],taskIds:["task"]})||contentHash(r.form)!==contentHash(form))throw new Error("evidence changed");},async execution(_c,_r,binding){const row=db.get<{configuration_hash:string;operation:string}>("SELECT * FROM executions WHERE id=?",[binding.executionId!]);if(!row||row.operation!==binding.operationId||row.configuration_hash!==binding.configurationHash)throw new Error("wrong execution");},async completeExecution(_c,record,result){const row=db.get<{sealed:number;result_hash:string}>("SELECT * FROM executions WHERE id=?",[record.execution!.executionId!]);if(!row?.sealed||result?.id!==record.execution!.executionId||result.contentHash!==row.result_hash)throw new Error("execution not sealed");},async assignee(c,id,r){await this.member({...c,actorId:id});await this.evidence(c,r);}};
  const repository:HumanReviewRepository={transaction(scope,callback){const result=queue.then(async()=>{db.exec("BEGIN IMMEDIATE");try{const value=await callback(createHumanReviewTransaction(db,scope,()=>{}));db.exec("COMMIT");return value;}catch(e){db.exec("ROLLBACK");throw e;}});queue=result.then(()=>{},()=>{});return result;}};
  let service=createHumanReviewService(repository,authority);const owner={scope:"team",actorId:"owner"},a={...owner,actorId:"rater-a"},b={...owner,actorId:"rater-b"},manager={...owner,actorId:"manager"};
  const create:HumanReviewCommand={action:"create",id:"review",operationId:"create",expectedRevision:0,projectId:"project",kind:"grade",title:"Task review",evidence,form,assigneeId:null,policy:{approval:"manager",minimumRaters:2,managerIds:["manager"],reviewerIds:["rater-a","rater-b"],queueClaim:true,teamVisible:true,independentRaters:true,distinctManager:true}};
  try{
    await service.command(owner,create);const claims=await Promise.allSettled([service.command(a,{action:"claim",id:"review",operationId:"claim-a",expectedRevision:1}),service.command(b,{action:"claim",id:"review",operationId:"claim-b",expectedRevision:1})]);expect(claims.filter(c=>c.status==="fulfilled")).toHaveLength(1);
    let record=await service.get(owner,"review");record=await service.command(a,{action:"save_draft",id:record.id,operationId:"draft",expectedRevision:record.revision,generation:record.generation,answers:[{criterionId:"quality",value:null,abstain:false,note:"unfinished rationale"}],note:"private draft"});
    expect((await service.view(b,record)).drafts).toEqual([]);
    const rating=[{criterionId:"quality",value:4,abstain:false,note:"Observed complete answer"}];let submit:HumanReviewCommand={action:"submit",id:record.id,operationId:"submit-a",expectedRevision:record.revision,generation:record.generation,evidenceHash:contentHash(evidence),formHash:contentHash(form),answers:rating,note:"first"};record=await service.command(a,submit);expect((await service.command(a,submit)).contentHash).toBe(record.contentHash);
    record=await service.command(b,{...submit,operationId:"submit-b",expectedRevision:record.revision,note:"second"});expect((await service.view(a,record)).submissions.map(s=>s.actorId)).toEqual(["rater-a"]);
    await expect(service.command(a,{action:"decide",id:record.id,operationId:"self-accept",expectedRevision:record.revision,outcome:"accept",submissions:record.submissions.map(s=>({id:s.id,contentHash:s.contentHash})),answers:rating,note:""})).rejects.toThrow();
    const accepted=await service.command(manager,{action:"decide",id:record.id,operationId:"accept",expectedRevision:record.revision,outcome:"accept",submissions:record.submissions.map(s=>({id:s.id,contentHash:s.contentHash})),answers:rating,note:"adjudicated"});expect(acceptedHumanEvidence(accepted,{reviewHash:accepted.contentHash,decisionHash:accepted.decisions.at(-1)!.contentHash}).answers).toEqual(rating);
    db.close();db=new NodeSqliteConnection(filename);service=createHumanReviewService(repository,authority);expect((await service.get(owner,"review")).contentHash).toBe(accepted.contentHash);
    // A lost execution admission response must resume the retained operation,
    // and in-progress or forged results must never become accepted contributions.
    const taskEvidence={...evidence,attempts:[],taskIds:["task"]};const execute=await service.command(owner,{...create,id:"execute",operationId:"execute-create",kind:"execute",evidence:taskEvidence,assigneeId:null,policy:{approval:"none",minimumRaters:1,managerIds:[],reviewerIds:[],queueClaim:false,teamVisible:false}});const configuration={request:{taskset:release,population:[{taskId:"task",receiptId:"fixed",seed:0}]}};
    const recover=async(record:import("@openpond/evals/human-review").HumanReview)=>{const row=db.get<{id:string}>("SELECT id FROM executions WHERE operation=?",[record.execution!.operationId]);return row?{id:row.id}:null;};const cancel=async(record:import("@openpond/evals/human-review").HumanReview)=>{db.run("UPDATE executions SET sealed=1 WHERE id=?",[record.execution!.executionId!]);};
    let providerCalls=0,lost=true;const dispatch=async(value:unknown)=>{const conf=value as {operationId:string};const id=`execution-${contentHash(conf.operationId)}`;if(!db.get("SELECT id FROM executions WHERE id=?",[id])){providerCalls++;db.run("INSERT INTO executions VALUES(?,?,?,0,?)",[id,conf.operationId,contentHash(value),contentHash("sealed output")]);}if(lost){lost=false;throw new Error("response lost");}return{id};};
    const request={endpoint:"execute" as const,scope:"team",id:execute.id,expectedRevision:execute.revision,generation:execute.generation,operationId:"initial-browser-operation",configuration};await expect(dispatchAssignedHumanExecution({service,context:owner,request,configuration,dispatch,recover:async()=>null,cancel})).rejects.toThrow("response lost");const bound=await dispatchAssignedHumanExecution({service,context:owner,request:{...request,operationId:"refreshed-browser-operation"},configuration,dispatch,recover,cancel});expect(providerCalls).toBe(1);expect(bound.execution?.executionId).toBeTruthy();
    const executeSubmit={...submit,id:bound.id,operationId:"execute-submit",expectedRevision:bound.revision,generation:bound.generation,evidenceHash:contentHash(taskEvidence),executionResult:{id:bound.execution!.executionId!,revision:1,contentHash:contentHash("sealed output")}} as HumanReviewCommand;await expect(service.command(owner,executeSubmit)).rejects.toThrow("execution not sealed");db.run("UPDATE executions SET sealed=1 WHERE id=?",[bound.execution!.executionId!]);const executed=await service.command(owner,executeSubmit);expect(executed.execution?.result?.contentHash).toBe(contentHash("sealed output"));
    // Failure story: cancellation races an actual retained owner admission.
    // The original run is found read-only, sealed into the cancelled assignment,
    // and cancelled without calling dispatch again after a lost response.
    const race=await service.command(owner,{...create,id:"race",operationId:"race-create",kind:"execute",evidence:taskEvidence,assigneeId:null,policy:{approval:"none",minimumRaters:1,managerIds:[],reviewerIds:[],queueClaim:false,teamVisible:false}});
    let allocated!:()=>void,releaseDispatch!:()=>void;const allocation=new Promise<void>(resolve=>{allocated=resolve;}),resume=new Promise<void>(resolve=>{releaseDispatch=resolve;});let raceCalls=0;
    const racingDispatch=async(value:unknown)=>{raceCalls++;const op=(value as {operationId:string}).operationId,id=`execution-${contentHash(op)}`;db.run("INSERT INTO executions VALUES(?,?,?,0,?)",[id,op,contentHash(value),contentHash("race output")]);allocated();await resume;throw new Error("lost allocated reply");};
    const racing=dispatchAssignedHumanExecution({service,context:owner,request:{...request,id:race.id,expectedRevision:race.revision,generation:race.generation,operationId:"race-start"},configuration,dispatch:racingDispatch,recover,cancel});
    await allocation;const reservedRace=await service.get(owner,race.id);await service.command(owner,{action:"cancel",id:race.id,operationId:"race-cancel",expectedRevision:reservedRace.revision,note:"cancel running assignment"});releaseDispatch();
    const cancelled=await racing;expect(cancelled.status).toBe("cancelled");expect(cancelled.execution?.executionId).toBeTruthy();expect(db.get<{sealed:number}>("SELECT sealed FROM executions WHERE id=?",[cancelled.execution!.executionId!])?.sealed).toBe(1);
    const recoveredRace=await dispatchAssignedHumanExecution({service,context:owner,request:{...request,id:race.id,expectedRevision:cancelled.revision,generation:race.generation,operationId:"race-refresh"},configuration,dispatch:racingDispatch,recover,cancel});expect(recoveredRace.status).toBe("cancelled");expect(raceCalls).toBe(1);
    const author=await service.command(owner,{...create,id:"author",operationId:"author-create",kind:"author",evidence:taskEvidence,assigneeId:"rater-b",policy:{approval:"manager",minimumRaters:1,managerIds:["manager"],reviewerIds:[],queueClaim:false,teamVisible:false}});const proposal=sealHumanTaskProposal([{taskId:"task",input:{prompt:"Revised task"},policyVisibleContext:{},expectedOutput:{protected:"owner reference"}}]);await expect(service.command(b,{...submit,id:author.id,expectedRevision:author.revision,generation:author.generation,operationId:"delegate-reference",taskProposal:proposal,evidenceHash:contentHash(taskEvidence)} as HumanReviewCommand)).rejects.toThrow("human_reference_edit_owner_required");const authored=await service.command(owner,{...submit,id:author.id,expectedRevision:author.revision,generation:author.generation,operationId:"owner-proposal",taskProposal:proposal,evidenceHash:contentHash(taskEvidence)} as HumanReviewCommand);const visible=await service.view(manager,authored);expect(visible.submissions[0]!.taskProposal?.tasks[0]).not.toHaveProperty("expectedOutput");expect(visible.submissions[0]!.taskProposal?.contentHash).toBe(proposal.contentHash);
    db.run("UPDATE grants SET enabled=0 WHERE actor=?",["rater-a"]);await expect(service.command(a,submit)).rejects.toThrow("revoked");await expect(service.get(a,"review",record.revision)).rejects.toThrow("revoked");
    const direct=await service.command(owner,{...create,id:"direct",operationId:"direct",policy:{approval:"none",minimumRaters:1,managerIds:[],reviewerIds:[],queueClaim:false,teamVisible:false},assigneeId:null});const done=await service.command(owner,{...submit,id:"direct",operationId:"direct-submit",expectedRevision:direct.revision,generation:direct.generation});expect(done.status).toBe("accepted");expect(done.assigneeId).toBeNull();
  }finally{db.close();await rm(home,{recursive:true,force:true});}
});
