import {z} from "zod";
import {HumanShareLocalRequestSchema,HumanEvidenceSchema,HumanFormSchema,ReviewReleaseSchema,HumanLocalPublicationsReadSchema,HumanRevokeLocalPublicationSchema} from "@openpond/evals/human-review";
import {LearningDomainError} from "@openpond/evals/learning";
import type {SqliteStore} from "../store/store.js";
import {exportLocalHumanEvidence} from "./local-export.js";
export async function shareLocalHumanEvidence(deps:{store:SqliteStore;actorId():Promise<string>;teamId():Promise<string>;hosted:{request(raw:unknown,signal?:AbortSignal):Promise<unknown>}},raw:unknown,signal?:AbortSignal){
 const request=HumanShareLocalRequestSchema.parse(raw),actorId=await deps.actorId(),teamId=await deps.teamId();
 async function current(){if(await deps.actorId()!==actorId||await deps.teamId()!==teamId||request.scope!==teamId)throw new LearningDomainError("human_scope_changed",403);}
 await current();
 const authority=z.object({scope:z.string(),actorId:z.string(),projectId:z.string()}).strict().parse(await deps.hosted.request({endpoint:"publication_access",scope:teamId,projectId:request.projectId},signal));if(authority.actorId!==actorId||authority.scope!==teamId||authority.projectId!==request.projectId)throw new LearningDomainError("human_publication_project_denied",403);
 await current();const evidence=await exportLocalHumanEvidence(deps,{endpoint:"export_local",scope:request.scope,projectId:request.projectId,graderId:request.graderId,selections:request.selections});await current();
 const published=z.object({evidence:HumanEvidenceSchema,form:HumanFormSchema}).strict().parse(await deps.hosted.request({endpoint:"publish_local",scope:teamId,projectId:request.projectId,operationId:request.operationId,audience:request.audience,workspaceVisible:request.workspaceVisible,evidence},signal));await current();
 const publication=ReviewReleaseSchema.parse(published.evidence.publication);if(published.evidence.attempts.some((attempt,index)=>attempt.experimentId!==evidence.attempts[index]?.executionId||attempt.attemptId!==evidence.attempts[index]?.receiptId)||published.evidence.attempts.length!==evidence.attempts.length)throw new LearningDomainError("human_publication_identity_changed",409);
 for(const attempt of evidence.attempts)await deps.store.rememberHumanLocalPublication({scope:teamId,actorId,executionId:attempt.executionId,executionHash:attempt.origin.executionHash,operationId:request.operationId,publication});await current();return published;
}
export async function readLocalHumanPublicationRefs(deps:{store:SqliteStore;actorId():Promise<string>;teamId():Promise<string>},raw:unknown){const request=HumanLocalPublicationsReadSchema.parse(raw),actorId=await deps.actorId();if(request.scope!==await deps.teamId())throw new LearningDomainError("human_scope_changed",403);const refs=z.array(ReviewReleaseSchema).max(1000).parse(await deps.store.humanLocalPublications({scope:request.scope,actorId,executionId:request.executionId}));if(actorId!==await deps.actorId()||request.scope!==await deps.teamId())throw new LearningDomainError("human_scope_changed",403);return refs;}

export async function revokeLocalHumanPublication(deps:{store:SqliteStore;actorId():Promise<string>;teamId():Promise<string>;hosted:{request(raw:unknown,signal?:AbortSignal):Promise<unknown>}},raw:unknown,signal?:AbortSignal){const request=HumanRevokeLocalPublicationSchema.parse(raw),actorId=await deps.actorId();if(request.scope!==await deps.teamId())throw new LearningDomainError("human_scope_changed",403);const result=z.object({revoked:z.literal(true)}).strict().parse(await deps.hosted.request({endpoint:"revoke_publication",scope:request.scope,publication:request.publication},signal));if(await deps.actorId()!==actorId||await deps.teamId()!==request.scope)throw new LearningDomainError("human_scope_changed",403);await deps.store.forgetHumanLocalPublication({scope:request.scope,actorId,publicationId:request.publication.id});return result;}
