import {inspectLocalHumanAttempt} from "./inspection.js";
import {publishLocalHumanTaskProposal} from "./task-publication.js";
import type {SqliteStore} from "../store/store.js";
import { z } from "zod";
import { contentHash } from "@openpond/harness";
import {projectAcceptedHumanComparison,type HumanComparisonSelections, HumanPublishAuthorRequestSchema,HumanAuthorTasksRequestSchema,HumanReviewRequestSchema, HumanGraderChoicesRequestSchema, HumanTasksSnapshotRequestSchema, HumanInspectRequestSchema, HumanExecuteRequestSchema, HumanExecutionReadRequestSchema, HumanResultsReadRequestSchema, createHumanResultView, dispatchAssignedHumanExecution, HumanEvidenceSchema, HumanFormSchema, createHumanReviewService, type HumanReview, type HumanReviewAuthority } from "@openpond/evals/human-review";
import { assertBoundedTaskJson } from "@openpond/evals/task-schema";
import { LearningDomainError } from "@openpond/evals/learning";
import type {ExperimentManifest,ExperimentResult} from "@openpond/evals/experiments";
import {RunExperimentSchema} from "openpond-sdk/experiments";
import {localHumanTasks} from "./tasks.js";
import { validateTasksetPackage } from "openpond-sdk/taskset-packages";
import { localRetainedCase } from "../evaluations/local-experiment-output.js";
import type { createLocalExperimentService } from "../evaluations/local-experiment-service.js";
const Snapshot = z.object({ endpoint:z.literal("snapshot"),scope:z.string().min(1),projectId:z.string().min(1),graderId:z.string().min(1),selections:z.array(z.object({executionId:z.string().min(1),receiptId:z.string().min(1)}).strict()).min(1).max(2) }).strict();

function fail(code:string,status:403|404|409|422=409):never {throw new LearningDomainError(code,status);}
export function createLocalHumanReviewRuntime(deps: { store:SqliteStore;storeDir:string; actorId:()=>Promise<string>; teamId:()=>Promise<string>; localExperiments:ReturnType<typeof createLocalExperimentService> }) {
  async function member(context:{scope:string;actorId:string}) {
    if (!context.actorId || context.actorId!==await deps.actorId() || context.scope!==await deps.teamId()) fail("human_local_scope_denied",403);
  }
  function snapshot(scope:string,actorId:string,projectId:string,graderId:string,selections:z.infer<typeof Snapshot>["selections"]) {
    let dataset:HumanReview["evidence"]["dataset"]|undefined,grader:HumanReview["evidence"]["grader"]|undefined,rubric:HumanReview["evidence"]["rubric"]|undefined,graderBinding:HumanReview["evidence"]["graderBinding"]|undefined,form:HumanReview["form"]|undefined;
    const attempts:HumanReview["evidence"]["attempts"]=[];
    for(const selection of selections) {
      const retained=deps.store.humanReviewLocalEvidence(scope,selection.executionId),definition=retained.released.definition;
      if(retained.execution.ownerActorId!==actorId||definition.ownerActorId!==actorId)fail("human_local_evidence_not_found",404);
      if(definition.configuration.request.project?.id!==projectId)fail("human_project_attempt_mismatch");
      if(!retained.execution.completedAt)fail("human_attempt_not_sealed");
      const value=validateTasksetPackage(retained.released.package),taskset=value.taskset;
      const compiled=taskset.graders.find(g=>g.id===graderId),pin=definition.graders.find(g=>g.id===graderId);
      if(!compiled||compiled.kind!=="human"||!compiled.form||!pin||pin.contentHash!==contentHash(compiled))fail("human_structured_grader_required");
      const caseRow=retained.cases.find(c=>c.receiptId===selection.receiptId);
      if(!caseRow?.result)fail("human_retained_behavior_unavailable");
      const evidence=localRetainedCase(caseRow.result),task=taskset.tasks.find(t=>t.id===caseRow.admission.taskId);
      if(!task)fail("human_task_unavailable");
      const nextDataset={id:taskset.id,revision:taskset.revision,contentHash:taskset.contentHash};
      const release=pin.release?{id:pin.release.id,revision:Number(pin.release.revision),contentHash:pin.release.contentHash}:{id:compiled.id,revision:Number(compiled.version),contentHash:contentHash(compiled)};
      if(!Number.isSafeInteger(release.revision)||release.revision<1)fail("human_grader_release_required");
      if(dataset&&contentHash(dataset)!==contentHash(nextDataset)||grader&&contentHash(grader)!==contentHash(release))fail("human_pair_releases_differ");
      dataset=nextDataset;grader=release;rubric={id:compiled.rubricRef.id,revision:1,contentHash:compiled.rubricRef.contentHash};graderBinding={id:compiled.id,version:compiled.version,contentHash:contentHash(compiled)};form=HumanFormSchema.parse(compiled.form);
      attempts.push({localSource:{kind:"native_local",ownerActorId:actorId,teamId:scope,executionHash:retained.execution.executionHash,configurationHash:contentHash(definition.configuration),retainedAttemptHash:evidence.attempt.contentHash,traceHash:evidence.attempt.native?.traceHash??evidence.attempt.profileNative?.traceHash??evidence.attempt.externalProcess?.traceHash??evidence.attempt.contentHash},experimentId:retained.execution.id,attemptId:caseRow.receiptId,taskId:task.id,targetId:definition.model.modelId,output:{id:caseRow.receiptId,revision:1,contentHash:evidence.attempt.contentHash},trace:{id:caseRow.receiptId,revision:1,contentHash:evidence.attempt.native?.traceHash??evidence.attempt.profileNative?.traceHash??evidence.attempt.externalProcess?.traceHash??evidence.attempt.contentHash},familyKey:task.clusterKey,split:task.split});
    }
    return {evidence:HumanEvidenceSchema.parse({dataset,grader,graderBinding,rubric,attempts}),form:HumanFormSchema.parse(form)};
  }
  const taskPackages=new Map<string,Awaited<ReturnType<typeof deps.localExperiments.readHumanTaskPackage>>>();
  const key=(scope:string,actorId:string,projectId:string,dataset:HumanReview["evidence"]["dataset"])=>contentHash([scope,actorId,projectId,dataset]);
  const publications=new Map<string,Awaited<ReturnType<typeof publishLocalHumanTaskProposal>>>();
  const authority:HumanReviewAuthority={ member,
    async owner(context,_projectId){await member(context);return true;},
    async evidence(context,record){await member(context);const exact=record.evidence.attempts.length?snapshot(context.scope,context.actorId,record.projectId,record.evidence.graderBinding.id,record.evidence.attempts.map(a=>({executionId:a.experimentId,receiptId:a.attemptId}))):localHumanTasks(taskPackages.get(key(context.scope,context.actorId,record.projectId,record.evidence.dataset))??fail("human_task_source_unavailable"),record.evidence.graderBinding.id,record.evidence.dataset,record.evidence.taskIds??[]);if(contentHash(exact.evidence)!==contentHash(record.evidence)||contentHash(exact.form)!==contentHash(record.form))fail("human_evidence_revision_changed");},
    async publication(_context,record,release,proposalHash){const value=publications.get(`${record.id}:${proposalHash}`);if(!value||value.taskset.id!==release.id||value.taskset.revision!==release.revision||value.taskset.contentHash!==release.contentHash)fail("human_task_publication_owner_unavailable");},
    async completeExecution(context,record,result){if(!result||!record.execution?.executionId)fail("human_execution_result_required");const retained=deps.store.humanReviewLocalEvidence(context.scope,record.execution.executionId);if(!retained.execution.completedAt||retained.execution.counts.pending||retained.execution.counts.running)fail("human_execution_not_sealed");const projected={execution:retained.execution,cases:retained.cases};if(result.id!==retained.execution.id||result.revision!==1||result.contentHash!==contentHash(projected))fail("human_execution_result_stale");},
    async execution(context,_record,binding){if(!binding.executionId)fail("human_execution_not_bound");const retained=deps.store.humanReviewLocalEvidence(context.scope,binding.executionId);if(retained.execution.ownerActorId!==context.actorId||retained.execution.operationId!==binding.operationId)fail("human_execution_binding_conflict");const {expectedRevision,...configuration}=retained.released.definition.configuration;void expectedRevision;if(contentHash(configuration)!==binding.configurationHash)fail("human_execution_binding_conflict");},
    async assignee(context,actorId,record){if(actorId!==context.actorId)fail("human_local_publish_required",403);await authority.evidence(context,record);},
  };
  const repository=deps.store.humanReviewRepository(),service=createHumanReviewService(repository,authority);
  return {async projectComparison(input:{scope:string;actorId:string;projectId:string;baseline:{manifest:ExperimentManifest;result:ExperimentResult};candidate:{manifest:ExperimentManifest;result:ExperimentResult};selections:HumanComparisonSelections}){
    const context={scope:input.scope,actorId:input.actorId};
    return projectAcceptedHumanComparison({...input,teamId:input.scope,authorize:()=>member(context),
      async readReview(ref){const review=await service.get(context,ref.id);if(review.revision!==ref.revision||review.contentHash!==ref.contentHash)fail("human_comparison_review_changed");const view=await service.view(context,review);if(!view.permissions.owner)fail("human_comparison_owner_required",403);return review;},
      async caseIdentity(attempt){await member(context);const retained=deps.store.humanReviewLocalEvidence(input.scope,attempt.experimentId);if(retained.execution.ownerActorId!==context.actorId||retained.released.definition.configuration.request.project?.id!==input.projectId)fail("human_comparison_source_denied",403);const receipt=retained.released.definition.configuration.request.population.find(p=>p.receiptId===attempt.attemptId);if(!receipt||receipt.taskId!==attempt.taskId)fail("human_comparison_receipt_changed");return{caseId:receipt.taskId,seed:receipt.seed,fixtureId:receipt.fixtureId};},
    });
  },async request(raw:unknown){
    assertBoundedTaskJson(raw,1_048_576);const scope=z.object({scope:z.string().min(1)}).parse(raw).scope,context={scope,actorId:await deps.actorId()};await member(context);
    // Resolve current source ACL outside the SQLite write queue; immutable bytes
    // can then be checked inside its atomic review transaction without deadlock.
    const taskRecords=await repository.transaction(scope,async tx=>{const envelope=z.object({id:z.string().optional(),command:z.object({id:z.string().optional(),action:z.string(),projectId:z.string().optional(),evidence:HumanEvidenceSchema.optional()}).passthrough().optional(),endpoint:z.string()}).passthrough().parse(raw);if(envelope.command?.action==="create")return envelope.command.evidence?[{projectId:envelope.command.projectId!,evidence:envelope.command.evidence}]:[];if(envelope.id||envelope.command?.id){const row=await tx.get(envelope.id??envelope.command!.id!);return row?[row]:[];}if(envelope.endpoint!=="inbox")return[];const rows:HumanReview[]=[];let cursor:string|undefined;do{const page=await tx.list({afterId:cursor,limit:100});rows.push(...page.items);cursor=page.nextCursor??undefined;}while(cursor);return rows;});
    for(const record of taskRecords)if(!record.evidence.attempts.length){const value=await deps.localExperiments.readHumanTaskPackage(scope,record.projectId,record.evidence.dataset);taskPackages.set(key(scope,context.actorId,record.projectId,record.evidence.dataset),value);}
    if(HumanGraderChoicesRequestSchema.safeParse(raw).success){const input=HumanGraderChoicesRequestSchema.parse(raw),value=await deps.localExperiments.readHumanTaskPackage(scope,input.projectId,input.dataset);return value.taskset.graders.flatMap(g=>g.kind==="human"&&g.form?[{id:g.id,name:g.rubricRef.id,version:g.version,contentHash:contentHash(g),mode:g.form.mode}]:[]);}
    if(HumanTasksSnapshotRequestSchema.safeParse(raw).success){const input=HumanTasksSnapshotRequestSchema.parse(raw),value=await deps.localExperiments.readHumanTaskPackage(scope,input.projectId,input.dataset);const taskIds=input.all?value.taskset.tasks.map(task=>task.id):input.taskIds!;if(taskIds.length>1000)fail("human_assignment_batch_limit_1000",422);return localHumanTasks(value,input.graderId,input.dataset,taskIds);}
    if(HumanPublishAuthorRequestSchema.safeParse(raw).success){const request=HumanPublishAuthorRequestSchema.parse(raw),review=await service.get(context,request.id),view=await service.view(context,review);if(!view.permissions.owner)fail("human_task_publication_owner_required",403);if(review.authorPublication){if(review.authorPublication.proposalHash!==request.proposalHash)fail("human_task_publication_stale");return view;}if(review.revision!==request.expectedRevision)fail("human_review_revision_stale");const baseline=taskPackages.get(key(scope,context.actorId,review.projectId,review.evidence.dataset))??fail("human_task_source_unavailable");const value=await publishLocalHumanTaskProposal({store:deps.store,storeDir:deps.storeDir,actorId:context.actorId,review,proposalHash:request.proposalHash,baseline});publications.set(`${review.id}:${request.proposalHash}`,value);return service.view(context,await service.command(context,{action:"bind_author_publication",id:review.id,operationId:request.operationId,expectedRevision:request.expectedRevision,proposalHash:request.proposalHash,dataset:{id:value.taskset.id,revision:value.taskset.revision,contentHash:value.taskset.contentHash}}));}
    if(HumanAuthorTasksRequestSchema.safeParse(raw).success){const input=HumanAuthorTasksRequestSchema.parse(raw),review=await service.get(context,input.id),view=await service.view(context,review);if(review.kind!=="author"||!view.permissions.reviewer&&!view.permissions.manager)fail("human_task_author_denied",403);if(input.includeReference&&!view.permissions.owner)fail("human_reference_read_owner_required",403);const value=taskPackages.get(key(scope,context.actorId,review.projectId,review.evidence.dataset))??fail("human_task_source_unavailable");return{dataset:review.evidence.dataset,tasks:(review.evidence.taskIds??[]).map(id=>{const task=value.taskset.tasks.find(t=>t.id===id)??fail("human_task_unavailable");return{taskId:id,input:task.input,policyVisibleContext:task.policyVisibleContext,...(input.includeReference?{expectedOutput:task.expectedOutput}:{}),tags:task.tags};})};}
    if(HumanExecuteRequestSchema.safeParse(raw).success){const request=HumanExecuteRequestSchema.parse(raw),review=await service.get(context,request.id),configuration=RunExperimentSchema.parse(request.configuration);if(configuration.request.project?.id!==review.projectId||contentHash(configuration.request.taskset)!==contentHash(review.evidence.dataset)||configuration.request.population.some(p=>!review.evidence.taskIds?.includes(p.taskId))||new Set(configuration.request.population.map(p=>p.taskId)).size!==review.evidence.taskIds?.length)fail("human_execution_resource_mismatch");if(configuration.graders&&!configuration.graders.some(g=>g.id===review.evidence.graderBinding.id&&g.version===review.evidence.graderBinding.version&&g.contentHash===review.evidence.graderBinding.contentHash))fail("human_execution_grader_mismatch");const result=await dispatchAssignedHumanExecution({service,context,request,configuration,dispatch:async(configuration)=>deps.localExperiments.runFromRelease({configuration}),recover:async record=>{const run=await deps.localExperiments.findRunOperation(scope,record.execution!.operationId);if(!run)return null;await authority.execution!(context,record,{...record.execution!,executionId:run.id});return{id:run.id};},cancel:async record=>{await member(context);await deps.localExperiments.cancel({teamId:scope,id:record.execution!.executionId!});}});return service.view(context,result);}
    if(HumanExecutionReadRequestSchema.safeParse(raw).success){const request=HumanExecutionReadRequestSchema.parse(raw),review=await service.get(context,request.id),view=await service.view(context,review);if(request.action==="cancel"&&!view.permissions.manager&&!view.permissions.reviewer)fail("human_execution_control_denied",403);if(!review.execution?.executionId)fail("human_execution_not_bound");return request.action==="cancel"?deps.localExperiments.cancel({teamId:scope,id:review.execution.executionId}):request.action==="result"?(async()=>{const descriptor=await repository.transaction(scope,async()=>{const retained=deps.store.humanReviewLocalEvidence(scope,review.execution!.executionId!);if(!retained.execution.completedAt)fail("human_execution_not_sealed");return{result:{id:retained.execution.id,revision:1,contentHash:contentHash({execution:retained.execution,cases:retained.cases})}};});return{...descriptor,evidence:await deps.localExperiments.result({teamId:scope,id:review.execution!.executionId!})};})():deps.localExperiments.status({teamId:scope,id:review.execution.executionId});}
    if(HumanResultsReadRequestSchema.safeParse(raw).success){const request=HumanResultsReadRequestSchema.parse(raw),execution=await deps.localExperiments.read({teamId:scope,id:request.executionId});const records=await repository.transaction(scope,async tx=>{const rows:HumanReview[]=[];let cursor:string|undefined;do{const page=await tx.list({afterId:cursor,limit:100});rows.push(...page.items.filter(r=>r.evidence.attempts.some(a=>a.experimentId===request.executionId)));cursor=page.nextCursor??undefined;}while(cursor);return rows;});const reviews=request.selection?await Promise.all(request.selection.map(async ref=>{const r=await service.get(context,ref.id,ref.revision);if(r.contentHash!==ref.contentHash)fail("human_result_selection_mismatch");return r;})):await Promise.all(records.map(r=>service.get(context,r.id)));return createHumanResultView({executionId:request.executionId,executionHash:execution.executionHash,reviews});}
    if(Snapshot.safeParse(raw).success){const input=Snapshot.parse(raw);return repository.transaction(scope,async()=>snapshot(scope,context.actorId,input.projectId,input.graderId,input.selections));}
    if(HumanInspectRequestSchema.safeParse(raw).success){const input=HumanInspectRequestSchema.parse(raw),review=await service.get(context,input.id);if(!review.evidence.attempts.length){const value=taskPackages.get(key(scope,context.actorId,review.projectId,review.evidence.dataset))??fail("human_task_source_unavailable");return (review.evidence.taskIds??[]).map((id,slotIndex)=>{const task=value.taskset.tasks.find(t=>t.id===id)??fail("human_task_unavailable");return{reviewId:review.id,reviewRevision:review.revision,evidenceHash:contentHash(review.evidence),slot:task.id,slotIndex,input:task.input,output:null,error:null,events:[],eventCount:0,evidenceLimited:false,nextEventCursor:null};});}if(input.slot!==undefined&&!review.evidence.attempts[input.slot])fail("human_inspection_slot_invalid");const projections=await Promise.all(review.evidence.attempts.map((_,slotIndex)=>slotIndex).filter(slotIndex=>input.slot===undefined||slotIndex===input.slot).map(slotIndex=>inspectLocalHumanAttempt({store:deps.store,experiments:deps.localExperiments,scope,review,slotIndex,...(input.afterId===undefined?{}:{afterId:input.afterId})})));const latest=await service.get(context,review.id);if(latest.revision!==review.revision)fail("human_inspection_revision_changed");return projections;}
    const input=HumanReviewRequestSchema.parse(raw);
    if(input.endpoint==="command") {
      const review=await service.command(context,input.command);
      // The sealed command is the durable cancellation intent. Replaying its
      // original operation retries the canonical runtime owner, never dispatch.
      if(input.command.action==="cancel"&&review.execution) {
        let current=await service.get(context,review.id);
        if(!current.execution?.executionId){
          const run=await deps.localExperiments.findRunOperation(scope,current.execution!.operationId);
          if(!run)throw new LearningDomainError("human_execution_admission_recovery_pending",409,"The original execution admission is unavailable. Recover its retained owner outcome before retrying cancellation.");
          current=await service.command(context,{action:"bind_execution",id:current.id,expectedRevision:current.revision,operationId:`bind-${current.execution!.operationId}`,generation:current.generation,runOperationId:current.execution!.operationId,configurationHash:current.execution!.configurationHash,executionId:run.id});
        }
        await member(context);
        await deps.localExperiments.cancel({teamId:scope,id:current.execution!.executionId!});
        return service.view(context,current);
      }
      return service.view(context,review);
    }
    if(input.endpoint==="get")return service.view(context,await service.get(context,input.id,input.revision));
    const page=await service.inbox(context,input);return{...page,items:await Promise.all(page.items.map(r=>service.view(context,r)))};
  }};
}
