import {promises as fs} from "node:fs";
import path from "node:path";
import {z} from "zod";
import {HarnessSourceManifestSchema} from "@openpond/contracts";
import {loadOpenPondProfileStateFromSource} from "@openpond/cloud";
import {canonicalJson,sha256,harnessPolicySourcePackageFiles} from "@openpond/harness";
import {verifyHostedProfileCandidateExport} from "openpond-sdk/experiment-improvements";
import {compileLocalHarnessSource,compileProfileHarnessSource,materializeLocalHarnessRelease} from "./harness/local-harness-workspace-service.js";
import {compiledCandidateExecutableIdentity} from "./harness/experiment-candidate-equivalence.js";
import {applyCandidateProfileSource,candidateGit} from "./harness/experiment-profile-git-source.js";
import type {ExperimentImprovementState} from "./harness/experiment-improvement-state.js";
const Input=z.object({action:z.enum(["stage","readback","rollback"]),repoPath:z.string(),outputDir:z.string(),exportFile:z.string(),commit:z.string().regex(/^[a-f0-9]{40}$/).optional(),expectedExecutableSourceHash:z.string().regex(/^[a-f0-9]{64}$/).optional()}).strict();
/** Trusted private worker IPC. It can stage a commit and compile readback, but
 * cannot select or advance the actual owner branch/publication pointer. */
export async function hostedProfileCandidate(raw:unknown){const input=Input.parse(raw);if(!path.isAbsolute(input.repoPath)||!path.isAbsolute(input.outputDir)||!/^[a-zA-Z0-9_-]+\.json$/.test(input.exportFile))throw new Error("Hosted candidate private IPC is not contained.");
 const file=path.join(input.outputDir,input.exportFile),stat=await fs.lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>8*1024*1024)throw new Error("Hosted candidate export exceeds its private IPC bound.");
 const value=verifyHostedProfileCandidateExport(JSON.parse(await fs.readFile(file,"utf8"))),profile=await loadOpenPondProfileStateFromSource({repoPath:input.repoPath,profileId:value.profileRef.profileId});if(profile.error||!profile.sourcePath)throw new Error("Actual hosted Profile source is unavailable.");
 if(input.action!=="readback"){let attached=false;try{await candidateGit(input.repoPath,["symbolic-ref","-q","HEAD"]);attached=true;}catch{}if(attached||await candidateGit(input.repoPath,["rev-parse","HEAD"])!==(input.action==="rollback"?input.commit:value.expectedCommit)||await candidateGit(input.repoPath,["status","--porcelain","--untracked-files=all"]))throw new Error("Candidate staging requires a clean detached exact original source worktree.");}
 const compile=async(sourceRevision:string)=>compileProfileHarnessSource({storeDir:input.outputDir,workspaceId:value.compiler.workspaceId,name:value.compiler.name,profile:await loadOpenPondProfileStateFromSource({repoPath:input.repoPath,profileId:value.profileRef.profileId}),sourceRevision,repositoryId:value.compiler.repositoryId});
 if(input.action==="readback"){if(!input.commit||await candidateGit(input.repoPath,["rev-parse","HEAD"])!==input.commit)throw new Error("Hosted Profile readback is not the committed source.");const compiled=await compile(input.commit),identity=compiledCandidateExecutableIdentity(compiled);if(identity.profileGitHead!==input.commit||identity.contentHash!==(input.expectedExecutableSourceHash??value.executableSourceHash)||identity.protectedClosureHash!==value.protectedClosureHash)throw new Error("Hosted active executable differs from the actual tested candidate.");const release=await materializeLocalHarnessRelease({storeDir:input.outputDir,workspaceId:value.compiler.workspaceId,compiled,createdAt:value.createdAt});return{commit:input.commit,activeRelease:{id:release.harnessRelease.id,contentHash:release.harnessRelease.contentHash},executableSourceHash:identity.contentHash,protectedClosureHash:identity.protectedClosureHash};}
 if(input.action==="rollback"){if(!input.commit)throw new Error("Rollback requires the exact accepted commit.");await candidateGit(input.repoPath,["-c","core.hooksPath=/dev/null","revert","--no-commit",input.commit]);}
 const baseline=await compile(value.expectedCommit);if(baseline.harnessRelease.contentHash!==value.baseRelease.contentHash||baseline.harnessRelease.id!==value.baseRelease.id)throw new Error("Hosted original source differs from the owner-attested baseline release.");
 if(input.action==="stage"){
  const manifestBytes=Buffer.from(value.sourceManifest.base64,"base64");if(manifestBytes.toString("base64")!==value.sourceManifest.base64||manifestBytes.length!==value.sourceManifest.sizeBytes||sha256(manifestBytes)!==value.sourceManifest.contentHash)throw new Error("Candidate source manifest byte identity differs.");const manifest=HarnessSourceManifestSchema.parse(JSON.parse(manifestBytes.toString("utf8"))),sourceDir=path.join(input.outputDir,"candidate-source");await fs.mkdir(sourceDir,{recursive:true});await fs.writeFile(path.join(sourceDir,"harness.json"),canonicalJson(manifest));const policy=harnessPolicySourcePackageFiles(value.policySource),privateFiles=new Map(baseline.sourceFiles.filter(row=>row.asset.visibility!=="policy").map(row=>[row.path,row]));
  for(const declaration of manifest.files){const bytes=declaration.visibility==="policy"?policy.get(declaration.path):privateFiles.get(declaration.path)?.bytes;if(!bytes)throw new Error("The hosted source cannot hydrate the exact protected candidate closure.");const target=path.join(sourceDir,declaration.path);if(path.relative(sourceDir,target).startsWith(".."))throw new Error("Candidate release path escapes private staging.");await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,bytes);}
  const candidate=await compileLocalHarnessSource({workspaceId:value.compiler.workspaceId,sourceDir}),identity=compiledCandidateExecutableIdentity(candidate);if(candidate.harnessRelease.contentHash!==value.policySource.harnessRelease.contentHash||identity.contentHash!==value.executableSourceHash||identity.protectedClosureHash!==value.protectedClosureHash)throw new Error("Owner-attested candidate differs from independently compiled hosted source.");
  await applyCandidateProfileSource({source:profile.sourcePath,state:{component:value.component} as ExperimentImprovementState,base:baseline,candidate,profile});
 }
 await candidateGit(input.repoPath,["add","--all"]);await candidateGit(input.repoPath,["-c","core.hooksPath=/dev/null","-c","commit.gpgSign=false","commit","-m",`${input.action==="rollback"?"Roll back":"Adopt"} owner-tested candidate ${value.candidateId}`],{GIT_AUTHOR_NAME:"OpenPond",GIT_AUTHOR_EMAIL:"profile-candidate@openpond.local",GIT_COMMITTER_NAME:"OpenPond",GIT_COMMITTER_EMAIL:"profile-candidate@openpond.local"});const commit=await candidateGit(input.repoPath,["rev-parse","HEAD"]),currentProfile=await loadOpenPondProfileStateFromSource({repoPath:input.repoPath,profileId:value.profileRef.profileId}),active=await compileProfileHarnessSource({storeDir:input.outputDir,workspaceId:value.compiler.workspaceId,name:value.compiler.name,profile:currentProfile,sourceRevision:commit,repositoryId:value.compiler.repositoryId}),identity=compiledCandidateExecutableIdentity(active);
 if(input.action==="stage"&&(identity.contentHash!==value.executableSourceHash||identity.protectedClosureHash!==value.protectedClosureHash)||input.action==="rollback"&&(identity.contentHash!==compiledCandidateExecutableIdentity(baseline).contentHash||identity.protectedClosureHash!==compiledCandidateExecutableIdentity(baseline).protectedClosureHash))throw new Error("Staged actual source differs from its exact tested executable graph.");
 return{commit,activeRelease:{id:active.harnessRelease.id,contentHash:active.harnessRelease.contentHash},executableSourceHash:identity.contentHash,protectedClosureHash:identity.protectedClosureHash};
}
export async function runHostedProfileCandidateCli(args:string[]){if(args.length!==1||args[0]!.length>16000||!/^[a-zA-Z0-9_-]+$/.test(args[0]!))throw new Error("Hosted candidate IPC argument is invalid.");process.stdout.write(`${JSON.stringify(await hostedProfileCandidate(JSON.parse(Buffer.from(args[0]!,"base64url").toString("utf8"))))}\n`);}
