#!/usr/bin/env node
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { z } from "zod";

import {
  AGENT_PROTOCOL_VERSION,
  AGENT_RPC_METHODS,
  AgentProtocolEnvelopeSchema,
} from "../src/protocol.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaOutputPath = path.join(root, "generated", "agent-protocol.schema.json");
const clientOutputPath = path.join(root, "src", "generated", "agent-rpc-client.ts");
const schemaOutput = `${JSON.stringify(z.toJSONSchema(AgentProtocolEnvelopeSchema, {
  target: "draft-7",
  unrepresentable: "any",
}), null, 2)}\n`;
const methodNames = {
  "runtime/capabilities": "capabilities",
  "thread/start": "threadStart",
  "thread/resume": "threadResume",
  "thread/read": "threadRead",
  "turn/start": "turnStart",
  "turn/steer": "turnSteer",
  "turn/interrupt": "turnInterrupt",
  "approval/resolve": "approvalResolve",
  "userInput/resolve": "userInputResolve",
  "harness/inspect": "harnessInspect",
  "harness/proposalReview": "harnessProposalReview",
  "harness/review": "harnessReview",
  "harness/validate": "harnessValidate",
  "harness/backgroundReview": "harnessBackgroundReview",
  "harness/diff": "harnessDiff",
  "harness/rollback": "harnessRollback",
} as const;
const requestMethods = AGENT_RPC_METHODS.filter(
  (method): method is keyof typeof methodNames => method in methodNames,
);
const clientOutput = `// Generated by scripts/generate-protocol-schema.ts. Do not edit.\n` +
  `import { AGENT_PROTOCOL_VERSION, type AgentRpcMethod } from "../protocol.js";\n\n` +
  `export type AgentRpcTransport = {\n` +
  `  request(method: AgentRpcMethod, params?: unknown): Promise<unknown>;\n` +
  `  notify(method: AgentRpcMethod, params?: unknown): Promise<void>;\n` +
  `};\n\n` +
  `export class AgentRpcClient {\n` +
  `  readonly #request: AgentRpcTransport["request"];\n` +
  `  readonly #notify: AgentRpcTransport["notify"];\n\n` +
  `  constructor(transport: AgentRpcTransport) {\n` +
  `    this.#request = transport.request.bind(transport);\n` +
  `    this.#notify = transport.notify.bind(transport);\n` +
  `  }\n\n` +
  `  async initialize(client: { name: string; version: string }, capabilities: Record<string, unknown> = {}) {\n` +
  `    const result = await this.#request("initialize", { protocolVersion: AGENT_PROTOCOL_VERSION, client, capabilities });\n` +
  `    await this.#notify("initialized");\n` +
  `    return result;\n` +
  `  }\n\n` +
  requestMethods.map((method) => {
    const defaultParams = method === "runtime/capabilities" || method.startsWith("harness/")
      ? " = {}"
      : "";
    return `  ${methodNames[method]} = (params: unknown${defaultParams}) => this.#request(${JSON.stringify(method)}, params);`;
  }).join("\n") +
  `\n}\n`;

if (process.argv.includes("--check")) {
  const [currentSchema, currentClient] = await Promise.all([
    readFile(schemaOutputPath, "utf8").catch(() => ""),
    readFile(clientOutputPath, "utf8").catch(() => ""),
  ]);
  if (currentSchema !== schemaOutput) throw new Error("Generated agent protocol schema is stale.");
  if (currentClient !== clientOutput) throw new Error("Generated agent RPC client is stale.");
} else {
  await Promise.all([
    mkdir(path.dirname(schemaOutputPath), { recursive: true }),
    mkdir(path.dirname(clientOutputPath), { recursive: true }),
  ]);
  await Promise.all([
    writeFile(schemaOutputPath, schemaOutput, "utf8"),
    writeFile(clientOutputPath, clientOutput, "utf8"),
  ]);
}
