import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { TasksetSchema, type GeneratedTaskFile, type Taskset } from "@openpond/contracts";
import { canonicalJson } from "./canonical-json.js";
import { validateTaskset } from "./validation.js";

export type TasksetBuildResult = {
  directory: string;
  files: string[];
  taskset: Taskset;
};

export async function buildTaskset(input: unknown, directory: string, options: { generatedFiles?: GeneratedTaskFile[] } = {}): Promise<TasksetBuildResult> {
  const taskset = TasksetSchema.parse(input);
  const report = validateTaskset(taskset);
  if (!report.valid) throw new Error(report.issues.map((issue) => `${issue.code}: ${issue.message}`).join("\n"));
  await mkdir(path.join(directory, "data"), { recursive: true });
  await mkdir(path.join(directory, "graders"), { recursive: true });
  await mkdir(path.join(directory, "environment"), { recursive: true });
  await mkdir(path.join(directory, "fixtures"), { recursive: true });
  const files = [
    path.join(directory, "taskset.json"),
    path.join(directory, "capabilities.json"),
    path.join(directory, "data", "tasks.jsonl"),
    path.join(directory, "graders", "graders.json"),
    path.join(directory, "fixtures", "grader-fixtures.json"),
    path.join(directory, "environment", "taskset.ts"),
  ];
  await writeFile(files[0]!, canonicalJson(taskset), "utf8");
  await writeFile(files[1]!, canonicalJson(taskset.capabilities), "utf8");
  await writeFile(files[2]!, taskset.tasks.map((task) => JSON.stringify(task)).join("\n") + "\n", "utf8");
  await writeFile(files[3]!, canonicalJson(taskset.graders), "utf8");
  await writeFile(files[4]!, canonicalJson(taskset.graderFixtures), "utf8");
  await writeFile(files[5]!, generatedEnvironmentSource(taskset), "utf8");
  for (const generated of options.generatedFiles ?? []) {
    const relative = safeGeneratedPath(generated.path, generated.role);
    const destination = path.join(directory, relative);
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, generated.content, "utf8");
    files.push(destination);
  }
  for (const grader of taskset.graders) {
    if (grader.kind !== "custom_verifier") continue;
    const relative = safeGeneratedPath(grader.module, "verifier");
    try { await access(path.join(directory, relative)); }
    catch { throw new Error(`Custom verifier ${grader.id} is missing generated source ${relative}.`); }
  }
  return { directory, files, taskset };
}

function safeGeneratedPath(value: string, role: GeneratedTaskFile["role"]): string {
  const normalized = value.replaceAll("\\", "/");
  if (path.posix.isAbsolute(normalized) || normalized.split("/").includes("..")) throw new Error(`Generated ${role} path must stay inside the Taskset: ${value}.`);
  const prefix = role === "verifier" ? "graders/" : role === "environment" ? "environment/" : "fixtures/";
  if (!normalized.startsWith(prefix)) throw new Error(`Generated ${role} path must start with ${prefix}.`);
  return normalized;
}

function generatedEnvironmentSource(taskset: Taskset): string {
  return `// Generated by @openpond/taskset-sdk.\nexport const environment = ${JSON.stringify(taskset.environment, null, 2)} as const;\nexport const tasks = ${JSON.stringify(taskset.tasks.map((task) => ({ id: task.id, input: task.input, split: task.split })), null, 2)} as const;\n`;
}

export async function inspectTaskset(file: string): Promise<{ taskset: Taskset; report: ReturnType<typeof validateTaskset> }> {
  const taskset = TasksetSchema.parse(JSON.parse(await readFile(file, "utf8")));
  return { taskset, report: validateTaskset(taskset) };
}
