import {
  CLI_GLOBAL_OPTION_SCHEMA,
  formatCliCommandUsage,
  listCliCommandDefinitions,
} from "./command-registry";

export function printHelp(): void {
  console.log(formatCliHelp());
}

export function formatCliHelp(): string {
  const lines = [
    "OpenPond CLI",
    "",
    "Usage:",
    "  openpond [--no-open] [--hostname HOST] [--port PORT]",
    "  openpond <command> [options] [-- passthrough...]",
    "  openpond --version",
    "",
    "Commands:",
  ];
  for (const definition of listCliCommandDefinitions()) {
    const aliases = definition.aliases?.length ? ` (aliases: ${definition.aliases.join(", ")})` : "";
    lines.push(`  ${definition.usage}${aliases}`);
    for (const usage of definition.usages ?? []) lines.push(`    ${usage}`);
  }
  lines.push("", "Global options:");
  for (const [name, kind] of Object.entries(CLI_GLOBAL_OPTION_SCHEMA).sort(([left], [right]) =>
    left.localeCompare(right)
  )) {
    const flag = name.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`);
    lines.push(kind === "boolean" ? `  --${flag}` : `  --${flag} <${kind}>`);
  }
  lines.push(
    "",
    "Run `openpond <command> --help` for the selected command schema.",
    "Arguments after `--` are passed through without option parsing.",
  );
  return lines.join("\n");
}

export function formatCliCommandReference(): string {
  const sections = listCliCommandDefinitions().map((definition) =>
    `## ${definition.name}\n\n\`\`\`text\n${formatCliCommandUsage(definition)}\n\`\`\``
  );
  return [
    "# OpenPond CLI command reference",
    "",
    "<!-- Generated by `pnpm --dir apps/cli docs:commands`; do not edit by hand. -->",
    "",
    "Parsing, aliases, command help, and this reference use the same authoritative registry.",
    "",
    ...sections,
    "",
  ].join("\n");
}
