// Tests in this manifest cross a real process, database, Git, filesystem,
// listener, package-build, or service boundary. Keep the list explicit so a
// fast unit run never changes meaning because of a filename heuristic.
export const ROOT_SYSTEM_TESTS = [
  "tests/persistence-boundaries.test.ts",
  "apps/server/src/**/*.test.ts",
  "tests/agent-app-server-cli.test.ts",
  "tests/agent-app-server-rpc.test.ts",
  "tests/app-preferences.test.ts",
  "tests/app-server-lean-composition.test.ts",
  "tests/bootstrap-event-window.test.ts",
  "tests/browser-control-queue.test.ts",
  "tests/byok-turn-runner-profile-tools.test.ts",
  "tests/chat-attachments.test.ts",
  "tests/cloud-api-core.test.ts",
  "tests/cloud-private-persistence.test.ts",
  "tests/codex-bridge-usage.test.ts",
  "tests/codex-history-file-index.test.ts",
  "tests/codex-history-revision.test.ts",
  "tests/codex-history.test.ts",
  "tests/codex-personal-skills.test.ts",
  "tests/command-artifacts.test.ts",
  "tests/desktop-backend-manager.test.ts",
  "tests/desktop-dev-smoke-script.test.ts",
  "tests/desktop-diagnostics-collector.test.ts",
  "tests/desktop-harness-runner.test.ts",
  "tests/desktop-runtime-stage.test.ts",
  "tests/desktop-server-token.test.ts",
  "tests/dev-runner.test.ts",
  "tests/development-system-context.test.ts",
  "tests/dpo-training.test.ts",
  "tests/github-extension-manager.test.ts",
  "tests/harness-refiner-benchmark-taskset.test.ts",
  "tests/hybrid-workspace-session.test.ts",
  "tests/learning-api.test.ts",
  "tests/learning-preparation.test.ts",
  "tests/local-project-actions.test.ts",
  "tests/local-project-source-upload.test.ts",
  "tests/logger-redaction.test.ts",
  "tests/manual-compaction-usage.test.ts",
  "tests/model-tool-registry.test.ts",
  "tests/model-project-authoring.test.ts",
  "tests/model-usage-store.test.ts",
  "tests/openpond-command-access.test.ts",
  "tests/openpond-resources.test.ts",
  "tests/profile-benchmark-git.test.ts",
  "tests/profile-source-upload.test.ts",
  "tests/project-agent-setup.test.ts",
  "tests/project-links.test.ts",
  "tests/project-workflow-state.test.ts",
  "tests/provider-diagnostics.test.ts",
  "tests/provider-scoped-payloads.test.ts",
  "tests/release-version.test.ts",
  "tests/remove-openpond-account.test.ts",
  "tests/resolved-training-bundle-release-isolation.test.ts",
  "tests/reward-model-qualification-store.test.ts",
  "tests/runtime-event-bus.test.ts",
  "tests/scripted-chat-provider.test.ts",
  "tests/server-event-page.test.ts",
  "tests/server-http-route-table.test.ts",
  "tests/server-http.test.ts",
  "tests/server-work-queues.test.ts",
  "tests/session-store.test.ts",
  "tests/sign-out-openpond-account.test.ts",
  "tests/signed-workspace-image-url.test.ts",
  "tests/sqlite-backup-retention.test.ts",
  "tests/sqlite-driver.test.ts",
  "tests/sqlite-store.test.ts",
  "tests/static-web-security.test.ts",
  "tests/subagent-store.test.ts",
  "tests/task-authoring-provenance.test.ts",
  "tests/task-creator-pipeline.test.ts",
  "tests/task-grader-execution.test.ts",
  "tests/taskset-authoring-skill.test.ts",
  "tests/taskset-draft-store.test.ts",
  "tests/taskset-draft.test.ts",
  "tests/taskset-work-assets.test.ts",
  "tests/taskset-work-attempt-runner.test.ts",
  "tests/taskset-work-generic-fixtures.test.ts",
  "tests/terminal-events.test.ts",
  "tests/terminal-one-shot.test.ts",
  "tests/terminal-process-ownership.test.ts",
  "tests/terminal-websocket-auth.test.ts",
  "tests/training-api-synthetic-preference.test.ts",
  "tests/training-artifact-package.test.ts",
  "tests/training-bundle.test.ts",
  "tests/training-chat-search.test.ts",
  "tests/update-openpond-account-config.test.ts",
  "tests/url-and-path-helpers.test.ts",
  "tests/voice-model-download.test.ts",
  "tests/work-agent-package-service.test.ts",
  "tests/work-output-service.test.ts",
  "tests/workspace-capabilities.test.ts",
  "tests/workspace-command.test.ts",
  "tests/workspace-diff.test.ts",
  "tests/workspace-lsp.test.ts",
  "tests/workspace-state.test.ts",
  "tests/workspace-tool-git.test.ts",
] as const;

export const ROOT_UI_TESTS = [
  "tests/**/*.test.tsx",
  "apps/web/src/**/*.test.tsx",
] as const;

export const ROOT_MEMORY_TESTS = [
  "tests/runtime-event-lists.test.ts",
] as const;

export const ROOT_IMAGE_TESTS = [
  "tests/local-image-tool-registry.test.ts",
] as const;
