import type { SqliteStore } from "./store.js";

/** Durable Harness operations shared by local and host-owned storage adapters. */
export type HarnessStateStore = Pick<SqliteStore,
  | "advanceHarnessWorkspaceAtomically"
  | "advanceReviewedHarnessWorkspaceAtomically"
  | "appendRuntimeEvent"
  | "createHarnessRunOverlay"
  | "createHarnessWorkspaceWithRelease"
  | "freezeHarnessRunOverlayWithProposalAtomically"
  | "getHarnessBackgroundReviewSettings"
  | "getHarnessEvaluationReviewSettings"
  | "getHarnessMemory"
  | "getHarnessRefinementCandidateByFingerprint"
  | "getHarnessReleaseRecord"
  | "getHarnessRunOverlay"
  | "getHarnessWorkspace"
  | "getProfileEvaluationComparison"
  | "getProfileEvaluationGrade"
  | "getProfileEvaluationReceipt"
  | "getProfileEvaluationRun"
  | "getProfileEvaluationSuiteRun"
  | "getSelectedHarnessWorkspace"
  | "getSession"
  | "getTurn"
  | "listHarnessAdvanceReceipts"
  | "listHarnessImprovementArtifacts"
  | "listHarnessMemories"
  | "listHarnessRefinementCandidates"
  | "listHarnessReleaseRecords"
  | "listHarnessWorkspaces"
  | "listModelUsageRecords"
  | "listPendingHarnessRefinerTriggers"
  | "listTasksetRevisions"
  | "rollbackHarnessWorkspaceAtomically"
  | "runtimeEventsForSession"
  | "runtimeEventsForTurn"
  | "saveHarnessCrossRunRefinementRequestIfAbsent"
  | "saveHarnessImprovementArtifact"
  | "saveHarnessRefinementCandidateTransition"
  | "saveHarnessReleaseRecord"
  | "saveProfileEvaluationComparison"
  | "saveProfileEvaluationGrade"
  | "saveProfileEvaluationReceipt"
  | "saveProfileEvaluationRun"
  | "saveProfileEvaluationSuiteRun"
  | "selectHarnessWorkspace"
  | "setHarnessBackgroundReviewSettings"
  | "setHarnessEvaluationReviewSettings"
  | "turnsForSession"
  | "updateHarnessWorkspaceSourceRevisionAtomically"
  | "updateTurn"
  | "upsertModelUsageRecord"
  | "writeHarnessMemory"
> & { readonly harnessStoragePlacement: "local" | "hosted" };

/** Operations required by background review; authoring controls are a separate authority. */
export type HarnessReviewStateStore = Pick<HarnessStateStore,
  | "getHarnessWorkspace" | "getHarnessReleaseRecord" | "saveHarnessReleaseRecord"
  | "getHarnessRunOverlay" | "createHarnessRunOverlay" | "freezeHarnessRunOverlayWithProposalAtomically"
  | "getHarnessBackgroundReviewSettings" | "listHarnessMemories" | "getHarnessMemory" | "writeHarnessMemory"
  | "saveHarnessImprovementArtifact" | "listHarnessImprovementArtifacts" | "listPendingHarnessRefinerTriggers"
  | "harnessStoragePlacement"
  | "advanceHarnessWorkspaceAtomically" | "advanceReviewedHarnessWorkspaceAtomically" | "rollbackHarnessWorkspaceAtomically"
  | "getSession" | "getTurn" | "updateTurn" | "turnsForSession" | "runtimeEventsForTurn" | "listModelUsageRecords"
>;
