import {contentHash} from "@openpond/harness";
import {requireLocalRuntimeOwner} from "./local-experiment-owner.js";
import {localExecution,localCases} from "./local-experiment-records.js";
import type {OpenPondSqliteConnection} from "./sqlite/sqlite-driver.js";
export type HumanLiveControlInput={teamId:string;actorId:string;ownerId:string;executionId:string;receiptId:string;sessionId:string;operationId:string;action:"message"|"seal";text?:string;phase:"prepare"|"acknowledge"};
type Receipt={replay:boolean;state:"prepared"|"acknowledged"};
export function writeHumanLiveControl(db:OpenPondSqliteConnection,input:HumanLiveControlInput):Receipt;
export function writeHumanLiveControl(db:OpenPondSqliteConnection,input:Omit<HumanLiveControlInput,"phase">&{phase:"inspect"}):Receipt|null;
export function writeHumanLiveControl(db:OpenPondSqliteConnection,input:Omit<HumanLiveControlInput,"phase">&{phase:HumanLiveControlInput["phase"]|"inspect"}){
 const execution=localExecution(db,input.teamId,input.executionId);if(execution.ownerActorId!==input.actorId)throw new Error("live_agent_account_denied");const owner=db.get<{owner_id:string}>("SELECT owner_id FROM local_experiment_executions WHERE team_id=? AND id=?",[input.teamId,input.executionId]);const member=localCases(db,input.teamId,input.executionId).find(row=>row.receiptId===input.receiptId);if(!member||member.admission.request.model.providerId!=="claude-code")throw new Error("live_agent_case_denied");
 const session=db.get<{payload:string}>("SELECT payload FROM local_experiment_events WHERE team_id=? AND execution_id=? AND case_id=? AND type='external.start' ORDER BY sequence LIMIT 1",[input.teamId,input.executionId,input.receiptId]);if(!session||JSON.parse(session.payload).sessionId!==input.sessionId)throw new Error("live_agent_session_stale");
 db.exec("CREATE TABLE IF NOT EXISTS human_live_controls(team_id TEXT NOT NULL,actor_id TEXT NOT NULL,operation_id TEXT NOT NULL,request_hash TEXT NOT NULL,state TEXT NOT NULL,PRIMARY KEY(team_id,actor_id,operation_id))");
 const {phase,ownerId,...content}=input;void phase;void ownerId;const requestHash=contentHash(content),prior=db.get<{request_hash:string;state:"prepared"|"acknowledged"}>("SELECT request_hash,state FROM human_live_controls WHERE team_id=? AND actor_id=? AND operation_id=?",[input.teamId,input.actorId,input.operationId]);if(prior&&prior.request_hash!==requestHash)throw new Error("live_agent_operation_conflict");
 if(input.phase==="inspect")return prior?{replay:true,state:prior.state}:null;
 requireLocalRuntimeOwner(db,input.ownerId);if(owner?.owner_id!==input.ownerId)throw new Error("live_agent_execution_lease_lost");
 if(input.phase==="acknowledge"){if(!prior)throw new Error("live_agent_operation_missing");if(prior.state==="acknowledged")return{replay:true,state:"acknowledged" as const};appendControlEvent(db,input,"external.control_receipt",{sessionId:input.sessionId,operationId:input.operationId,action:input.action,transport:"process_stdin",state:"acknowledged",occurredAt:new Date().toISOString()});db.run("UPDATE human_live_controls SET state='acknowledged' WHERE team_id=? AND actor_id=? AND operation_id=?",[input.teamId,input.actorId,input.operationId]);return{replay:false,state:"acknowledged" as const};}
 if(prior)return{replay:true,state:prior.state};
 const uncertain=db.get("SELECT c.operation_id FROM human_live_controls c JOIN local_experiment_events e ON e.team_id=c.team_id AND json_extract(e.payload,'$.actorId')=c.actor_id AND json_extract(e.payload,'$.operationId')=c.operation_id WHERE c.team_id=? AND c.actor_id=? AND c.state='prepared' AND e.execution_id=? AND e.case_id=? AND e.type='external.human_intervention' LIMIT 1",[input.teamId,input.actorId,input.executionId,input.receiptId]);if(uncertain)throw new Error("live_agent_prior_delivery_unknown");
 if(member.status!=="running"||execution.completedAt)throw new Error("live_agent_already_sealed");
 db.run("INSERT INTO human_live_controls VALUES(?,?,?,?,'prepared')",[input.teamId,input.actorId,input.operationId,requestHash]);appendControlEvent(db,input,"external.human_intervention",{...content,occurredAt:new Date().toISOString()});return{replay:false,state:"prepared" as const};
}

function appendControlEvent(db:OpenPondSqliteConnection,input:Omit<HumanLiveControlInput,"phase">,type:string,value:unknown){const payload=JSON.stringify(value),bytes=Buffer.byteLength(payload),budget=db.get<{event_count:number;byte_count:number}>("SELECT event_count,byte_count FROM local_experiment_trace_budgets WHERE team_id=? AND execution_id=?",[input.teamId,input.executionId]);if(bytes>1048576||(budget?.event_count??0)>=20000||(budget?.byte_count??0)+bytes>67108864)throw new Error("live_agent_control_too_large");db.run("INSERT INTO local_experiment_events(team_id,execution_id,case_id,type,payload) VALUES(?,?,?,?,?)",[input.teamId,input.executionId,input.receiptId,type,payload]);db.run("INSERT INTO local_experiment_trace_budgets(team_id,execution_id,event_count,byte_count) VALUES(?,?,1,?) ON CONFLICT(team_id,execution_id) DO UPDATE SET event_count=event_count+1,byte_count=byte_count+excluded.byte_count",[input.teamId,input.executionId,bytes]);}
