export const MUTATING_WORKSPACE_TOOL_ACTIONS = [
  "write_file",
  "write_files",
  "edit_file",
  "delete_file",
  "git_init",
  "create_sandbox_template_scaffold",
  "build_sandbox_template",
  "run_sandbox_template",
  "sandbox_upload_file",
  "sandbox_write_file",
  "sandbox_edit_file",
  "sandbox_delete_file",
  "sandbox_mkdir",
  "sandbox_move_file",
  "sandbox_exec",
  "sandbox_git_branch",
  "sandbox_git_commit",
  "sandbox_git_pull",
  "sandbox_git_push",
  "sandbox_run_action",
] as const;
