import {useEffect,useMemo,useRef,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {contentHash} from "@openpond/harness";
import {ExperimentImprovementListSchema,ExperimentImprovementClient,ExperimentImprovementOptionsSchema,verifyExperimentImprovementState,type ExperimentImprovementState,type ExperimentImprovementCommand} from "openpond-sdk/experiment-improvements";
import type {ExperimentManifest,ExperimentResult} from "@openpond/evals/experiments";
import {WorkspacePanel,useWorkspaceActions} from "./WorkspacePanel";
import type {WorkspaceApi} from "./workspace-api";
import {useDraftNavigation} from "../useDraftNavigation";
import {useRetainedImprovementStart} from "./useRetainedImprovementStart";
import {ExperimentImproveCandidate} from "./ExperimentImproveCandidate";
/** Lives in the existing Experiment sidebar. Collapsing retains this editor;
 * switching account/Project/evidence remounts and drops stale candidate state. */
export function ExperimentImproveSidebar({api,evidence,onOpenWork}:{api:WorkspaceApi;evidence:{manifest:ExperimentManifest;result:ExperimentResult}|null;onOpenWork?:(sessionId:string)=>void}){
  const [open,setOpen]=useState(false),[opened,setOpened]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),guard=useDraftNavigation({name:"candidate edits",dirty,busy,onLeave:()=>setOpen(false)});
  useWorkspaceActions(evidence?.result.status==="completed"?[{id:"improve",label:"Improve",onSelect:()=>{setOpened(true);setOpen(true); }}]:[]);
  return <>{opened&&evidence?<WorkspacePanel label="Improve" action="improve" visible={open} onRequestClose={()=>void guard.requestLeave(()=>setOpen(false))}><ImproveSetup key={contentHash([api.key,api.connection.serverUrl,api.connection.token,evidence.manifest.id,evidence.result.contentHash])} api={api} evidence={evidence} onOpenWork={onOpenWork} onDirty={setDirty} onBusy={setBusy}/></WorkspacePanel>:null}{guard.dialog}</>;
}
function ImproveSetup({api,evidence,onOpenWork,onDirty,onBusy}:{api:WorkspaceApi;evidence:{manifest:ExperimentManifest;result:ExperimentResult};onOpenWork?:(id:string)=>void;onDirty:(dirty:boolean)=>void;onBusy:(busy:boolean)=>void}){
  const client=useMemo(()=>{if(!api.actorId)throw new Error("Sign in before improving this Experiment.");return new ExperimentImprovementClient({baseUrl:api.connection.serverUrl,apiKey:api.connection.token,teamId:api.teamId,actorId:api.actorId});},[api]),queryClient=useQueryClient(),reference={id:evidence.manifest.id,contentHash:evidence.result.contentHash},queryKey=["experiment-improve",api.key,reference.id,reference.contentHash];
  async function pages(signal?:AbortSignal){const states:ExperimentImprovementState[]=[];let cursor:string|undefined;for(let pageIndex=0;pageIndex<200;pageIndex++){const page=ExperimentImprovementListSchema.parse(await client.command({operation:"list",limit:50,...(cursor?{cursor}:{})},signal));states.push(...page.states.map(verifyExperimentImprovementState));if(!page.nextCursor)return states;if(cursor&&page.nextCursor<=cursor)throw new Error("Candidate discovery did not advance its retained scan.");cursor=page.nextCursor;}throw new Error("Candidate discovery exceeded its bounded page count. Retry the original retained operation directly.");}
  const options=useQuery({queryKey:[...queryKey,"options"],queryFn:async({signal})=>ExperimentImprovementOptionsSchema.parse(await client.command({operation:"options",evidence:reference},signal))}),history=useQuery({queryKey:[...queryKey,"history"],queryFn:async({signal})=>{return (await pages(signal)).filter(state=>state.evidence.manifest.id===reference.id&&state.evidence.result.contentHash===reference.contentHash&&state.projectId===api.projectId);}});
  const [ownerId,setOwnerId]=useState(""),[componentId,setComponentId]=useState(""),[mode,setMode]=useState<"manual"|"llm_assisted">("manual"),[modelId,setModelId]=useState(""),[budget,setBudget]=useState(1),[testBudget,setTestBudget]=useState(1),[steps,setSteps]=useState(30),[minutes,setMinutes]=useState(10),[candidate,setCandidate]=useState<ExperimentImprovementState|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),inFlight=useRef(false),mounted=useRef(true),pending=useRef<AbortController|null>(null),startOperation=useRef(crypto.randomUUID());
  const journal=useRetainedImprovementStart({scope:[api.key,api.connection.serverUrl,api.actorId,api.teamId,api.projectId,reference],actorId:api.actorId!,teamId:api.teamId,projectId:api.projectId,evidence:reference,client,onRecovered:setCandidate});
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;pending.current?.abort();};},[]);
  useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
  const owner=options.data?.profiles.find(profile=>profile.id===ownerId),component=owner?.components.find(row=>contentHash([row.kind,row.path,row.workflowId])===componentId);
  useEffect(()=>{if(!options.data?.profiles.some(profile=>profile.id===ownerId)){setOwnerId(options.data?.profiles[0]?.id??"");setComponentId("");}},[options.data,ownerId]);
  useEffect(()=>{if(owner&&!owner.components.some(row=>contentHash([row.kind,row.path,row.workflowId])===componentId))setComponentId(owner.components[0]?contentHash([owner.components[0].kind,owner.components[0].path,owner.components[0].workflowId]):"");},[owner,componentId]);
  const models=useQuery({queryKey:[...queryKey,"models"],queryFn:({signal})=>api.request<{available:boolean;unavailableReason:string|null;models:Array<{id:string;name:string}>}>("modelChoices",{taskset:evidence.manifest.dataset},signal)});
  async function command(request:ExperimentImprovementCommand){if(inFlight.current)return;journal.invalidateRecovery();inFlight.current=true;setBusy(true);setError(null);const controller=new AbortController();pending.current=controller;try{if(request.operation==="start")await journal.retain(request);const result=verifyExperimentImprovementState(await client.command(request,controller.signal));if(!mounted.current)return;if(request.operation==="start")await journal.clear(request);setCandidate(result);onDirty(false);await queryClient.invalidateQueries({queryKey:[...queryKey,"history"]});}catch(cause){if(!mounted.current)return;if(request.operation==="start"){const recovered=await pages(controller.signal).catch(()=>null);if(recovered){const value=recovered.find(state=>state.operationId===request.request.operationId&&state.requestHash===contentHash(request.request));if(value&&mounted.current){await journal.clear(request);setCandidate(value);return;}}}else if("id" in request){const recovered=await client.command({operation:"read",id:request.id},controller.signal).catch(()=>null);if(recovered&&mounted.current){const value=verifyExperimentImprovementState(recovered);if(value.id===request.id&&(!candidate||value.revision>candidate.revision)){setCandidate(value);return;}}}setError(cause instanceof Error?cause.message:String(cause));}finally{inFlight.current=false;if(mounted.current)setBusy(false);if(pending.current===controller)pending.current=null;}}
  const polling=useQuery({queryKey:[...queryKey,"candidate",candidate?.id],enabled:Boolean(candidate&&["authoring_queued","authoring","testing","adopting"].includes(candidate.status)),queryFn:async({signal})=>verifyExperimentImprovementState(await client.command({operation:"read",id:candidate!.id},signal)),refetchInterval:3000});
  useEffect(()=>{if(polling.data&&candidate?.id===polling.data.id&&polling.data.revision>=candidate.revision)setCandidate(polling.data);},[polling.data,candidate]);
  const failure=error??journal.error??options.error?.message??history.error?.message??polling.error?.message??models.error?.message;
  return <div className="evaluation-form"><h2>Improve</h2><p>Keep the original evidence, create a separate source candidate, and test the exact frozen revision against the same Dataset and graders.</p>{failure?<p role="alert">{failure}</p>:null}
    {candidate?<><label>Test budget per run USD<input type="number" min="0.000001" step="0.1" disabled={busy||candidate.test!==null} value={testBudget} onChange={event=>setTestBudget(Number(event.target.value))}/></label><p>Maximum paired test spend: {(2*(candidate.test?.recipe.maximumCostUsd??testBudget)).toFixed(6)} USD, plus {(2*(candidate.test?.recipe.scoring?.maximumCostUsd??options.data?.scoring?.maximumCostUsd??0)).toFixed(6)} USD for grading.</p><ExperimentImproveCandidate key={candidate.id} client={client} humanContext={api.humanContext} candidate={candidate} busy={busy} command={command} recipe={candidate.test?.recipe??(component?{externalDatasetBinding:component.binding,...(options.data?.scoring?{scoring:options.data.scoring}:{}),modelId,maximumCostUsd:testBudget}:null)} modelId={modelId} onModelChange={setModelId} onOpenWork={onOpenWork} models={models.data?.models??[]} onDirty={onDirty} onClose={()=>{if(!busy){setCandidate(null);onDirty(false);startOperation.current=crypto.randomUUID();}}}/></>:<>
      <label>Existing candidate<select value="" onChange={event=>{const value=history.data?.find(state=>state.id===event.target.value);if(value){setCandidate(value);const profile=options.data?.profiles.find(row=>contentHash(row.profileRef)===contentHash(value.profileRef));setOwnerId(profile?.id??"");setComponentId(contentHash([value.component.kind,value.component.path,value.component.workflowId]));}}}><option value="">Start a new candidate</option>{history.data?.map(state=><option key={state.id} value={state.id}>{state.component.kind} {state.status} revision {state.revision}</option>)}</select></label>
      <label>Profile<select value={ownerId} onChange={event=>setOwnerId(event.target.value)}><option value="">Select Profile</option>{options.data?.profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label>
      <label>Component<select value={componentId} onChange={event=>setComponentId(event.target.value)}><option value="">Select component</option>{owner?.components.map(row=><option key={contentHash([row.kind,row.path,row.workflowId])} value={contentHash([row.kind,row.path,row.workflowId])}>{row.kind} {row.label}</option>)}</select></label>
      {options.isPending?<p>Loading authorized source choices…</p>:!options.data?.profiles.some(profile=>profile.components.length)?<p>No qualifying source component is available. Select a clean, committed Profile and publish the exact Dataset with released graders before retrying.</p>:null}
      <label>Mode<select value={mode} onChange={event=>setMode(event.target.value==="manual"?"manual":"llm_assisted")}><option value="manual">Manual</option><option value="llm_assisted">LLM Assisted</option></select></label>
      <label>Model<select value={modelId} onChange={event=>setModelId(event.target.value)}><option value="">Select model</option>{models.data?.models.map(model=><option key={model.id} value={model.id}>{model.name}</option>)}</select></label>{models.data?.unavailableReason?<p>{models.data.unavailableReason}</p>:null}
      <label>Authoring budget USD<input type="number" min="0.000001" step="0.1" value={budget} onChange={event=>setBudget(Number(event.target.value))}/></label>
      <label>Test budget per run USD<input type="number" min="0.000001" step="0.1" value={testBudget} onChange={event=>setTestBudget(Number(event.target.value))}/></label>
      <p>Maximum paired test spend: {(testBudget*2).toFixed(6)} USD, plus up to {budget.toFixed(6)} USD for authoring.</p>
      <label>Maximum authoring steps<input type="number" min="1" max="500" value={steps} onChange={event=>setSteps(Number(event.target.value))}/></label>
      <label>Maximum authoring minutes<input type="number" min="1" max="1440" value={minutes} onChange={event=>setMinutes(Number(event.target.value))}/></label>
      <button className="training-button" disabled={busy||!journal.ready||(!journal.pending&&(!owner||!component))||!models.data?.models.some(model=>model.id===modelId)||mode==="manual"&&component?.kind==="agent"} onClick={()=>{if(journal.pending){void command(journal.pending);return;}if(owner&&component)void command({operation:"start",request:{operationId:startOperation.current,ownerWorkspaceId:owner.ownerWorkspaceId,expectedOwnerRevision:owner.ownerRevision,baseRelease:owner.baseRelease,profileRef:owner.profileRef,profileSourceRevision:owner.profileSourceRevision,projectId:api.projectId,evidence:reference,component:{kind:component.kind,path:component.path,...(component.workflowId?{workflowId:component.workflowId}:{})},mode,limits:{maximumCostUsd:budget,maximumAuthoringSteps:steps,maximumDurationMs:minutes*60000}}});}}>{journal.pending?"Recover original creation":"Create candidate"}</button>
    </>}
  </div>;
}
