import { useQuery } from "@tanstack/react-query";
import type { ExperimentHistoryPage } from "openpond-sdk/experiments";
import type { ModelsRoute } from "../models-route";
import type { WorkspaceApi } from "./workspace-api";
import { EvaluationModel, EvaluationStatus, EvaluationTime } from "./EvaluationPresentation";
export function ExperimentHistory({ api, route, navigate }: { api: WorkspaceApi; route: ModelsRoute; navigate: (route: ModelsRoute) => void }) {
  const history = useQuery({ queryKey: ["evaluation-workspace", api.key, "executionHistory", route.query, route.after], queryFn: ({ signal }) => api.request<ExperimentHistoryPage>("executionHistory", { search: route.query, ...(route.after ? { afterId: route.after } : {}) }, signal), refetchInterval: query => query.state.data?.items.some(({ summary }) => ["queued", "running", "cancelling"].includes(summary.status)) ? 2_000 : false });
  return <><label>Search history <input value={route.query} onChange={event => navigate({ ...route, query: event.target.value, after: null })} /></label>{history.error ? <p role="alert">{history.error.message} <button onClick={() => void history.refetch()}>Retry</button></p> : null}<table className="training-data-table evaluation-workspace-table"><thead><tr><th>Experiment</th><th>Target</th><th>Dataset</th><th>Status</th><th>Cases</th><th>Started</th></tr></thead><tbody>{history.data?.items.map(({ summary, definition, policy }) => { const destination = { ...route, collection: "default" as const, resourceId: definition.id, executionId: summary.id, passId: null, detailTab: "cases" }; return <tr key={summary.id}><td><button className="training-text-button" onClick={() => navigate(destination)}>{summary.name}</button></td><td><EvaluationModel name={"modelId" in policy ? policy.modelId : "Authored fixtures"} onOpen={() => navigate({ ...destination, detailTab: "configuration" })} /></td><td>v{summary.taskset.revision}</td><td><EvaluationStatus status={summary.status} /></td><td>{summary.counts.completed + summary.counts.failed + summary.counts.cancelled}/{summary.totalCount}</td><td><EvaluationTime value={summary.createdAt} /></td></tr>; })}{history.isPending ? <tr><td colSpan={6} role="status">Loading history…</td></tr> : history.data?.items.length === 0 ? <tr><td colSpan={6}>No executions in this view.</td></tr> : null}</tbody></table>{route.after ? <button className="training-button secondary" onClick={() => navigate({ ...route, after: null })}>Newest executions</button> : null}{history.data?.nextCursor ? <button className="training-button secondary" onClick={() => navigate({ ...route, after: history.data!.nextCursor })}>Older executions</button> : null}</>;
}
