import {HumanComparisonChooser} from "../../human-review/HumanComparisonChooser";
import {humanRequest,type HumanInboxContext} from "../../human-review/api";
import {useEffect,useMemo,useRef,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {compareExperiments} from "@openpond/evals/experiments";
import {ExperimentComparisonTables} from "./ExperimentComparisonTables";
import {z} from "zod";
import {useDraftNavigation} from "../useDraftNavigation";
import type {ExperimentImprovementClient,ExperimentImprovementState,ExperimentImprovementCommand,ExperimentImprovementTestRecipe} from "openpond-sdk/experiment-improvements";
const Instructions=z.object({candidateId:z.string(),candidateRevision:z.number(),path:z.string(),text:z.string(),textHash:z.string(),contentHash:z.string()}).strict();
export function ExperimentImproveCandidate({client,candidate,busy,command,recipe,modelId,onModelChange,onOpenWork,onDirty,onClose,models,humanContext}:{humanContext?:HumanInboxContext|null;client:ExperimentImprovementClient;candidate:ExperimentImprovementState;busy:boolean;command:(value:ExperimentImprovementCommand)=>Promise<void>;recipe:ExperimentImprovementTestRecipe|null;modelId:string;onModelChange:(id:string)=>void;onOpenWork?:(id:string)=>void;onDirty?:(dirty:boolean)=>void;models:Array<{id:string;name:string}>;onClose:()=>void}){
  const [humanDirty,setHumanDirty]=useState(false);
  const [feedbackKey,setFeedbackKey]=useState(""),[text,setText]=useState(""),[prompt,setPrompt]=useState("Improve the selected component using the retained evaluation evidence. Preserve all other source and private evaluation boundaries."),instructions=useQuery({queryKey:["improve-instructions",candidate.actorId,candidate.teamId,candidate.id,candidate.revision],enabled:candidate.mode==="manual"&&candidate.status==="draft",queryFn:async({signal})=>Instructions.parse(await client.command({operation:"instructions",id:candidate.id},signal))});
  const manualDraft=useRef<{text:string;baseHash:string}|null>(null);
  useEffect(()=>{if(instructions.data){if(!manualDraft.current||manualDraft.current.text===instructions.data.text){manualDraft.current={text:instructions.data.text,baseHash:instructions.data.contentHash};setText(instructions.data.text);}}},[instructions.data]);
  useEffect(()=>{onDirty?.(humanDirty||candidate.mode==="manual"&&instructions.data!==undefined&&text!==instructions.data.text||candidate.mode==="llm_assisted"&&candidate.status==="draft"&&prompt!=="Improve the selected component using the retained evaluation evidence. Preserve all other source and private evaluation boundaries.");},[humanDirty,candidate.mode,candidate.status,instructions.data,text,prompt,onDirty]);
  const dirty=humanDirty||candidate.mode==="manual"&&Boolean(instructions.data&&text!==instructions.data.text)||candidate.mode==="llm_assisted"&&candidate.status==="draft"&&prompt!=="Improve the selected component using the retained evaluation evidence. Preserve all other source and private evaluation boundaries.",guard=useDraftNavigation({name:"candidate edits",dirty,busy,onLeave:onClose});
  const comparison=useMemo(()=>candidate.comparison?compareExperiments(candidate.comparison.baseline,candidate.comparison.candidate):undefined,[candidate.comparison]);
  const action=(operation:"freeze"|"finishAuthoring"|"useCandidate"|"discard"|"cancel"|"rollback")=>command({operation,id:candidate.id,revision:candidate.revision});
  return <section><h3>{candidate.component.kind} candidate</h3><p>{candidate.status}, revision {candidate.revision}</p><p>Original source {candidate.baseRelease.contentHash.slice(0,16)}. Evidence {candidate.evidence.result.contentHash.slice(0,16)}.</p>{candidate.error?<p role="alert">{candidate.error}</p>:null}{instructions.error?<p role="alert">{instructions.error.message}</p>:null}{candidate.status==="draft"&&candidate.component.kind!=="agent"?<label>Authoring mode<select disabled={busy} value={candidate.mode} onChange={event=>void command({operation:"mode",id:candidate.id,revision:candidate.revision,mode:event.target.value==="manual"?"manual":"llm_assisted"})}><option value="manual">Manual</option><option value="llm_assisted">LLM Assisted</option></select></label>:null}
    {candidate.status==="draft"&&candidate.mode==="manual"?<><label>Candidate instructions<textarea rows={18} value={text} onChange={event=>{setText(event.target.value);if(instructions.data)manualDraft.current={text:event.target.value,baseHash:manualDraft.current?.baseHash??instructions.data.contentHash};}} maxLength={250000}/></label><button disabled={busy||!instructions.data||text===instructions.data.text} onClick={()=>{if(instructions.data)void command({operation:"edit",id:candidate.id,revision:candidate.revision,expectedFileHash:manualDraft.current?.baseHash??instructions.data.contentHash,text});}}>Save candidate instructions</button><button disabled={busy||!instructions.data||text===instructions.data.text} onClick={()=>{if(instructions.data){manualDraft.current={text:instructions.data.text,baseHash:instructions.data.contentHash};setText(instructions.data.text);}}}>Discard unsaved editor changes</button></>:null}
    {candidate.status==="draft"&&candidate.mode==="llm_assisted"?<><label>Authoring model<select value={modelId} onChange={event=>onModelChange(event.target.value)}><option value="">Select model</option>{models.map(model=><option key={model.id} value={model.id}>{model.name}</option>)}</select></label><label>Improve instructions<textarea value={prompt} onChange={event=>setPrompt(event.target.value)} rows={6} maxLength={20000}/></label><button disabled={busy||!models.some(model=>model.id===modelId)||!prompt.trim()} onClick={()=>void command({operation:"author",id:candidate.id,revision:candidate.revision,modelId,prompt})}>Start Work authoring</button></>:null}
    {candidate.work?<p>Work turn {candidate.work.turnId}{onOpenWork?<button onClick={()=>onOpenWork(candidate.work!.sessionId)}>Open authoring Work</button>:null}</p>:null}
    {candidate.status==="draft"?<button disabled={busy||candidate.mode==="manual"&&instructions.data?.text!==text} onClick={()=>void action("freeze")}>Freeze candidate</button>:null}
    {candidate.frozen?<><p>Frozen source {candidate.frozen.release.contentHash.slice(0,16)}. Protected closure {candidate.frozen.protectedClosureHash.slice(0,16)}.</p><details><summary>Source changes ({candidate.frozen.diff.length})</summary>{candidate.frozen.diff.map(row=><p key={row.path}>{row.path}: {row.before?.slice(0,12)??"added"} → {row.after?.slice(0,12)??"removed"}</p>)}</details></>:null}
    {candidate.status==="frozen"?<><label>Test model<select value={modelId} onChange={event=>onModelChange(event.target.value)}><option value="">Select model</option>{models.map(model=><option key={model.id} value={model.id}>{model.name}</option>)}</select></label><p>Run both the original and frozen component using the same ordered {recipe?.externalDatasetBinding.population.length??0} cases, Dataset release and grading settings.</p><button disabled={busy||!recipe||!recipe.modelId.trim()} onClick={()=>{if(recipe)void command({operation:"test",id:candidate.id,revision:candidate.revision,recipe});}}>Test baseline and candidate</button></>:null}
    {candidate.status==="testing"?<p>The actual baseline and candidate executions retain their own output, usage, traces and grading. This panel will show the matched comparison when both finish.</p>:null}
    {candidate.status==="testing"&&humanContext&&humanContext.actorId===candidate.actorId&&humanContext.scope===candidate.teamId?<HumanComparisonChooser key={`${candidate.actorId}:${candidate.teamId}:${candidate.id}`} state={candidate} busy={busy} readOptions={()=>client.command({operation:"humanComparisonOptions",id:candidate.id})} reviewRequest={(request,signal)=>humanRequest(humanContext,request,signal)} onCompare={command} onDirty={setHumanDirty}/>:null}
    {candidate.comparison?<><h4>Matched comparison</h4><p>Baseline {candidate.comparison.baseline.result.contentHash.slice(0,16)}. Candidate {candidate.comparison.candidate.result.contentHash.slice(0,16)}.</p><ExperimentComparisonTables data={comparison} loading={false} retry={()=>{}} graders={[]} feedbackKey={feedbackKey} onFeedbackKey={setFeedbackKey}/></>:null}
    {candidate.status==="ready_for_review"?<button disabled={busy} onClick={()=>void action("useCandidate")}>Use candidate</button>:null}
    {candidate.status==="accepted"?<><p>Adopted with receipt {candidate.acceptance?.contentHash.slice(0,16)}.</p><button disabled={busy} onClick={()=>void action("rollback")}>Roll back original Profile</button></>:null}
    {candidate.status==="rolled_back"?<p>Rolled back with receipt {candidate.rollback?.contentHash.slice(0,16)}.</p>:null}
    {["authoring_queued","authoring","testing"].includes(candidate.status)?<button disabled={busy} onClick={()=>void action("cancel")}>Cancel active work</button>:null}
    {["draft","frozen","ready_for_review","failed"].includes(candidate.status)?<button disabled={busy} onClick={()=>void action("discard")}>Decline candidate</button>:null}<button disabled={busy} onClick={()=>void guard.requestLeave(onClose)}>Back to candidates</button>{guard.dialog}
  </section>;
}
