import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { feedbackKeyForReward, type GraderCatalogPageSchema, type GraderVersionsPageSchema, type RewardRelease } from "openpond-sdk/learning";
import type { z } from "zod";
import type { WorkspaceApi } from "./workspace-api";
export function GraderReleasePicker({ api, value, onChange }: { api: WorkspaceApi; value: RewardRelease | null; onChange: (reward: RewardRelease | null) => void }) {
  const [search, setSearch] = useState("");
  const [after, setAfter] = useState<string | undefined>();
  const [id, setId] = useState(value?.id ?? "");
  const [beforeRevision, setBefore] = useState<number | undefined>();
  const catalog = useQuery({ queryKey: ["evaluation-workspace", api.key, "graderPicker", search, after], queryFn: ({ signal }) => api.request<z.infer<typeof GraderCatalogPageSchema>>("graderCatalog", { allProjects: true, search, ...(after ? { after } : {}) }, signal) });
  const versions = useQuery({ queryKey: ["evaluation-workspace", api.key, "graderPickerVersions", id, beforeRevision], enabled: Boolean(id), queryFn: ({ signal }) => api.request<z.infer<typeof GraderVersionsPageSchema>>("graderVersions", { id, ...(beforeRevision ? { beforeRevision } : {}) }, signal) });
  return <fieldset><legend>Published grader release</legend><label>Find grader<input value={search} onChange={event => { setSearch(event.target.value); setAfter(undefined); }} /></label><label>Grader<select value={id} onChange={event => { setId(event.target.value); setBefore(undefined); onChange(null); }}><option value="">Choose grader</option>{id && !catalog.data?.items.some(item => item.reward.id === id) ? <option value={id}>{value?.name ?? id}</option> : null}{catalog.data?.items.map(({ reward }) => <option key={reward.id} value={reward.id} disabled={["human", "learned_model"].includes(reward.implementation.kind)}>{reward.name} · {feedbackKeyForReward(reward)}</option>)}</select></label>{catalog.data?.nextCursor ? <button type="button" className="training-text-button" onClick={() => setAfter(catalog.data!.nextCursor!)}>More graders</button> : null}{after ? <button type="button" className="training-text-button" onClick={() => setAfter(undefined)}>First grader page</button> : null}{id ? <><label>Immutable release<select value={value?.contentHash ?? ""} onChange={event => onChange(versions.data?.items.find(reward => reward.contentHash === event.target.value) ?? null)}><option value="">Choose release</option>{value && !versions.data?.items.some(item => item.contentHash === value.contentHash) ? <option value={value.contentHash}>{value.name} · Revision {value.revision}</option> : null}{versions.data?.items.map(reward => <option key={reward.revision} value={reward.contentHash}>{reward.name} · Revision {reward.revision} · {feedbackKeyForReward(reward)}</option>)}</select></label>{versions.data?.nextRevision ? <button type="button" className="training-text-button" onClick={() => setBefore(versions.data!.nextRevision!)}>Older releases</button> : null}{beforeRevision ? <button type="button" className="training-text-button" onClick={() => setBefore(undefined)}>Newest releases</button> : null}</> : null}{value ? <p>{feedbackKeyForReward(value)} · {value.contentHash}{value.implementation.kind === "model_judge" ? ` · Calibration ${value.implementation.calibrationStatus}` : ""}</p> : null}{catalog.error || versions.error ? <p role="alert">{catalog.error?.message ?? versions.error?.message}</p> : null}</fieldset>;
}
