import { EvaluationCard, EvaluationModel, EvaluationStatus } from "./EvaluationPresentation";
import { ExperimentHistory } from "./ExperimentHistory";
import { ExperimentCompare } from "./ExperimentCompare";
import { useWorkspaceActions, useWorkspaceResourceName } from "./WorkspacePanel";
import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { experimentDefinitionRef, type ExperimentDefinition, type ExperimentScoringPass } from "openpond-sdk/experiments";
import type { ModelTasksetRunDetails } from "openpond-sdk/model-taskset-runs";
import type { ModelsRoute } from "../models-route";
import { ExperimentSetupPanel } from "./ExperimentSetupPanel";
import { ExperimentCases } from "./ExperimentCases";
import type { ExperimentEvidence, Inventory, WorkspaceApi } from "./workspace-api";
export function HostedExperimentsPage({ api, inventory, route, navigate, refresh }: { api: WorkspaceApi; inventory: Inventory | null; route: ModelsRoute; navigate: (route: ModelsRoute) => void; refresh: () => void }) {
  const [setup, setSetup] = useState(false);
  const [busy, setBusy] = useState(false);
  const activeMutation = useRef(false);
  const [error, setError] = useState<string | null>(null);
  const definition = useQuery({ queryKey: ["evaluation-workspace", api.key, "definition", route.resourceId], enabled: Boolean(route.resourceId), queryFn: ({ signal }) => api.request<ExperimentDefinition>("definition", { id: route.resourceId }, signal) });
  const history = useQuery({ queryKey: ["evaluation-workspace", api.key, "executions", route.resourceId], enabled: Boolean(route.resourceId), queryFn: ({ signal }) => api.request<{ items: ModelTasksetRunDetails[]; nextCursor: string | null }>("executions", { id: route.resourceId }, signal), refetchInterval: current => current.state.data?.items.some(run => ["queued", "running", "cancelling"].includes(run.summary.status)) ? 2_000 : false });
  const executionId = route.executionId ?? history.data?.items[0]?.summary.id ?? null;
  const execution = useQuery({ queryKey: ["evaluation-workspace", api.key, "execution", executionId], enabled: Boolean(executionId), queryFn: ({ signal }) => api.request<ModelTasksetRunDetails>("execution", { id: executionId }, signal), refetchInterval: current => current.state.data && ["queued", "running", "cancelling"].includes(current.state.data.summary.status) ? 2_000 : false });
  const passes = useQuery({ queryKey: ["evaluation-workspace", api.key, "passes", executionId], enabled: Boolean(executionId), queryFn: ({ signal }) => api.request<{ items: ExperimentScoringPass[]; nextCursor: string | null }>("passes", { id: executionId }, signal), refetchInterval: current => current.state.data?.items.some(pass => ["queued", "running", "cancelling"].includes(pass.status)) ? 2_000 : false });
  const selectedPass = passes.data?.items.find(pass => pass.id === route.passId);
  const evidence = useQuery({ queryKey: ["evaluation-workspace", api.key, "result", executionId, route.passId], enabled: Boolean(route.passId ? selectedPass?.resultAvailable : execution.data?.summary.resultAvailable), queryFn: ({ signal }) => api.request<ExperimentEvidence>(route.passId ? "passResult" : "result", { id: route.passId ?? executionId }, signal) });
  async function mutate(action: () => Promise<void>) {
    if (activeMutation.current) return; activeMutation.current = true; setBusy(true); setError(null);
    try { await action(); await Promise.all([history.refetch(), executionId ? execution.refetch() : Promise.resolve(), executionId ? passes.refetch() : Promise.resolve()]); refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { activeMutation.current = false; setBusy(false); }
  }
  function start() { const saved = definition.data; if (!saved) return; void mutate(async () => { const operation = api.operation("start", experimentDefinitionRef(saved)); const run = await api.request<ModelTasksetRunDetails>("start", { operationId: operation.id, definition: experimentDefinitionRef(saved) }); navigate({ ...route, executionId: run.summary.id, passId: null, detailTab: "cases" }); }); }
  function rerun() { if (!executionId) return; void mutate(async () => { const operation = api.operation("retry", { executionId }); const run = await api.request<ModelTasksetRunDetails>("retry", { id: executionId, operationId: operation.id }); operation.acknowledge(); navigate({ ...route, executionId: run.summary.id, passId: null, detailTab: "cases" }); }); }
  const selectSidebarAction = useWorkspaceActions([{ id: "experiment", label: "Experiment", onSelect: () => setSetup(true) }]);
  const saved = definition.data;
  const run = execution.data;
  const tab = route.detailTab ?? "overview";
  const target = saved?.request.policy;
  const model = target && "modelId" in target ? target.modelId : null;
  useWorkspaceResourceName(saved?.request.name ?? (definition.error ? "Unavailable experiment" : null));
  return <><header className="evaluation-workspace-header"><h1>{saved?.request.name ?? "Experiments"}</h1>{saved ? <><button className="training-button secondary" disabled={busy} onClick={() => selectSidebarAction("experiment")}>Edit setup</button><button className="training-button" disabled={busy} onClick={start}>Start</button></> : <button className="training-button" onClick={() => selectSidebarAction("experiment")}>+ Experiment</button>}</header>
    {!route.resourceId ? <nav className="evaluation-workspace-tabs" aria-label="Experiment collection tabs">{["default", "history"].map(collection => <button key={collection} aria-selected={route.collection === collection} onClick={() => navigate({ ...route, collection: collection as "default" | "history", after: null, query: "" })}>{collection === "default" ? "Experiments" : "History"}</button>)}</nav> : null}
    {error || definition.error || history.error || execution.error || evidence.error ? <p role="alert">{error ?? definition.error?.message ?? history.error?.message ?? execution.error?.message ?? evidence.error?.message}</p> : null}
    {!route.resourceId && route.collection === "history" ? <ExperimentHistory api={api} route={route} navigate={navigate} /> : saved ? <><p>{target?.kind === "hosted_harness" ? `${target.source.target.kind} · ${target.source.definitionId}` : "Model"}{model ? <> · <EvaluationModel name={model} onOpen={() => navigate({ ...route, detailTab: "configuration" })} /></> : ""} · Revision {saved.revision}</p>
      <nav className="evaluation-workspace-tabs" aria-label="Experiment tabs">{["overview", "cases", "compare", "configuration"].map(value => <button key={value} aria-selected={tab === value} onClick={() => navigate({ ...route, detailTab: value })}>{value[0]!.toUpperCase() + value.slice(1)}</button>)}</nav>
      <div className="evaluation-workspace-scope"><label>Execution <select value={executionId ?? ""} onChange={event => navigate({ ...route, executionId: event.target.value, passId: null })}><option value="">Choose execution</option>{history.data?.items.map(item => <option key={item.summary.id} value={item.summary.id}>{new Date(item.summary.createdAt).toLocaleString()} · {item.summary.status} · {item.summary.id}</option>)}</select></label>{run ? <button className="training-button secondary" disabled={busy} onClick={rerun}>Run again</button> : null}{run && ["queued", "running", "cancelling"].includes(run.summary.status) ? <button className="training-button secondary" disabled={busy || run.summary.status === "cancelling"} onClick={() => void mutate(async () => { await api.request("cancel", { id: executionId }); })}>Cancel</button> : null}</div>
      {run ? <p><EvaluationStatus status={run.summary.status} /> · {run.summary.counts.completed}/{run.summary.totalCount} completed · {run.summary.cleanupComplete ? "Cleanup complete" : "Cleanup pending"}{run.summary.error ? ` · ${run.summary.error.message}` : ""}</p> : null}
      {passes.data?.items.length ? <label>Scoring <select value={route.passId ?? ""} onChange={event => navigate({ ...route, passId: event.target.value || null })}><option value="">Original execution grading</option>{passes.data.items.map(pass => <option value={pass.id} key={pass.id}>{pass.id} · {pass.status}</option>)}</select></label> : null}
      {tab === "configuration" ? <EvaluationCard title="Configuration"><dl className="evaluation-workspace-meta"><dt>Dataset</dt><dd>{saved.request.taskset.id} · Revision {saved.request.taskset.revision}</dd><dt>Dataset hash</dt><dd>{saved.request.taskset.contentHash}</dd><dt>Budget</dt><dd>${saved.maximumCostUsd} · Policy and graders combined</dd><dt>Target</dt><dd><EvaluationModel name={model ?? target?.kind ?? "Unknown"} /></dd><dt>Population</dt><dd>{saved.request.population.length} cases</dd><dt>Graders</dt><dd>{saved.graders.map(grader => `${grader.feedbackKey} · ${grader.id} · ${grader.version}`).join("; ")}</dd><dt>Source</dt><dd>{target?.kind === "hosted_harness" ? target.source.sourceRevision : "Hosted model"}</dd></dl></EvaluationCard> : tab === "compare" ? <ExperimentCompare key={`${executionId}:${route.passId ?? "original"}`} api={api} inventory={inventory} definitionId={saved.id} baselineId={route.passId ?? executionId} /> : evidence.data && !setup ? <ExperimentCases evidence={evidence.data} api={api} execution={run ?? null} saved={saved} busy={busy} onScore={action => void mutate(action)} onSelectPass={passId => navigate({ ...route, passId, detailTab: "cases" })} /> : <p role="status">{run ? "Waiting for retained case results…" : "Save setup, then Start to create an execution."}</p>}
    </> : <><label>Search experiments <input value={route.query} onChange={event => navigate({ ...route, query: event.target.value, after: null })} /></label><table className="training-data-table evaluation-workspace-table"><thead><tr><th>Experiment</th><th>Target</th><th>Dataset</th><th>Revision</th></tr></thead><tbody>{inventory?.experiments.items.map(item => <tr key={item.id} tabIndex={0} onClick={() => navigate({ ...route, resourceId: item.id, detailTab: "overview" })} onKeyDown={event => { if (event.key === "Enter") navigate({ ...route, resourceId: item.id, detailTab: "overview" }); }}><td>{item.request.name}</td><td><EvaluationModel name={"modelId" in item.request.policy ? item.request.policy.modelId : "Fixture"} onOpen={() => navigate({ ...route, resourceId: item.id, detailTab: "configuration" })} /></td><td>{item.request.taskset.id}</td><td>{item.revision}</td></tr>)}</tbody></table>{inventory?.experiments.nextCursor ? <button onClick={() => navigate({ ...route, after: inventory.experiments.nextCursor })}>More experiments</button> : null}{inventory && !inventory.experiments.items.length ? <p>No experiments in this Project.</p> : null}</>}
    {setup ? <ExperimentSetupPanel api={api} inventory={inventory} existing={saved ?? null} onClose={() => setSetup(false)} onSaved={value => { setSetup(false); refresh(); navigate({ ...route, resourceId: value.id, detailTab: "configuration", executionId: null, passId: null }); }} /> : null}
  </>;
}
