import { EvaluationTime } from "./EvaluationPresentation";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { DatasetPopulationPage } from "openpond-sdk/dataset-workspaces";
import type { HostedTasksetSummary } from "openpond-sdk/taskset-catalog";
import type { ModelsRoute } from "../models-route";
import type { Inventory, WorkspaceApi } from "./workspace-api";
import { WorkspacePanel, useWorkspaceResourceName } from "./WorkspacePanel";

export function ReleasedDatasetDetail({ api, inventory, route, navigate }: { api: WorkspaceApi; inventory: Inventory | null; route: ModelsRoute; navigate: (value: ModelsRoute) => void }) {
  const [afterId, setAfter] = useState<string | undefined>();
  const [taskId, setTaskId] = useState<string | null>(null);
  const summary = useQuery({ queryKey: ["evaluation-workspace", api.key, "catalogDataset", route.resourceId], queryFn: ({ signal }) => api.request<HostedTasksetSummary>("catalogDataset", { id: route.resourceId }, signal) });
  const population = useQuery({ queryKey: ["evaluation-workspace", api.key, "releasedDatasetTasks", summary.data?.release.contentHash, afterId], enabled: Boolean(summary.data), queryFn: ({ signal }) => api.request<DatasetPopulationPage>("datasetPopulation", { release: summary.data!.release, view: "policy", limit: 25, ...(afterId ? { afterId } : {}) }, signal) });
  const task = population.data?.items.find(item => item.id === taskId);
  const tab = route.detailTab ?? "tasks";
  useWorkspaceResourceName(summary.data?.name ?? (summary.error ? "Unavailable Dataset" : null));
  return <><header className="evaluation-workspace-header"><h1>{summary.data?.name ?? "Dataset"}</h1></header>{summary.error || population.error ? <p role="alert">{summary.error?.message ?? population.error?.message}</p> : null}{summary.isPending ? <p role="status">Loading released Dataset…</p> : null}{summary.data ? <><p>{summary.data.description}</p><p>Published revision {summary.data.release.revision} · {summary.data.taskCount} tasks</p><nav className="evaluation-workspace-tabs" aria-label="Dataset tabs">{["tasks", "experiments", "graders", "versions"].map(value => <button key={value} aria-selected={tab === value} onClick={() => { setTaskId(null); navigate({ ...route, detailTab: value }); }}>{value[0]!.toUpperCase() + value.slice(1)}</button>)}</nav>
    {tab === "tasks" ? <><table className="training-data-table evaluation-workspace-table"><thead><tr><th>Task</th><th>Input</th><th>Split</th></tr></thead><tbody>{population.data?.items.map(item => <tr key={item.id} tabIndex={0} onClick={() => setTaskId(item.id)} onKeyDown={event => { if (event.key === "Enter") setTaskId(item.id); }}><td>{item.id}</td><td>{"input" in item ? JSON.stringify(item.input).slice(0, 200) : ""}</td><td>{item.split}</td></tr>)}</tbody></table>{afterId ? <button onClick={() => { setAfter(undefined); setTaskId(null); }}>First tasks</button> : null}{population.data?.nextCursor ? <button onClick={() => { setAfter(population.data!.nextCursor!); setTaskId(null); }}>More tasks</button> : null}</> : tab === "graders" ? <table className="training-data-table"><thead><tr><th>Feedback key</th><th>Version</th><th>Released grader</th></tr></thead><tbody>{population.data?.graders.map(grader => <tr key={grader.id}><td>{grader.feedbackKey}</td><td>{grader.version}</td><td>{grader.release ? <button className="training-text-button" onClick={() => navigate({ ...route, page: "graders", resourceId: grader.release!.id, datasetKind: undefined, detailTab: "overview" })}>{grader.release.id} · Revision {grader.release.revision}</button> : "Dataset-owned"}</td></tr>)}</tbody></table> : tab === "experiments" ? <ul>{inventory?.experiments.items.filter(item => item.request.taskset.contentHash === summary.data!.release.contentHash).map(item => <li key={item.id}><button className="training-text-button" onClick={() => navigate({ ...route, page: "experiments", resourceId: item.id, datasetKind: undefined, detailTab: "overview" })}>{item.request.name}</button></li>)}</ul> : <dl className="evaluation-workspace-meta"><dt>Release</dt><dd>{summary.data.release.id} · Revision {summary.data.release.revision}</dd><dt>Content hash</dt><dd>{summary.data.release.contentHash}</dd><dt>Package bytes</dt><dd>{summary.data.packageBytes ?? "Unknown"}</dd><dt>Published</dt><dd><EvaluationTime value={summary.data.createdAt} /></dd></dl>}
  </> : null}{task && "input" in task ? <WorkspacePanel label="Task inspector"><header><h2>{task.id}</h2><button onClick={() => setTaskId(null)}>Close</button></header><h3>Input</h3><pre>{JSON.stringify(task.input, null, 2)}</pre><h3>Policy context</h3><pre>{JSON.stringify(task.policyVisibleContext, null, 2)}</pre><h3>Policy artifacts</h3><pre>{JSON.stringify(task.artifacts, null, 2)}</pre></WorkspacePanel> : null}</>;
}
