import {DatasetAssignments} from "../../human-review/DatasetAssignments";
import { EvaluationTableState } from "./EvaluationTableState";
import { DatasetExperiments } from "./DatasetExperiments";
import { DatasetTaskCheckbox, DatasetTaskSelection, useDatasetTaskSelection } from "./DatasetTaskSelection";
import { EvaluationCard, EvaluationTime } from "./EvaluationPresentation";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { DatasetPopulationPage } from "openpond-sdk/dataset-workspaces";
import type { HostedTasksetSummary } from "openpond-sdk/taskset-catalog";
import type { ModelsRoute } from "../models-route";
import type { Inventory, WorkspaceApi } from "./workspace-api";
import { WorkspacePanel, useWorkspaceResourceName, useWorkspaceActions, useWorkspacePanelControls } from "./WorkspacePanel";

export function ReleasedDatasetDetail({ api, route, navigate }: { api: WorkspaceApi; inventory: Inventory | null; route: ModelsRoute; navigate: (value: ModelsRoute) => void }) {
  const [afterId, setAfter] = useState<string | undefined>();
  const controls = useWorkspacePanelControls();
  const [taskId, setTaskId] = useState<string | null>(null);
  const summary = useQuery({ queryKey: ["evaluation-workspace", api.key, "catalogDataset", route.resourceId, route.revision, route.contentHash], queryFn: async ({ signal }) => { const value = await api.request<HostedTasksetSummary>("catalogDataset", { id: route.resourceId }, signal); if (route.contentHash && (value.release.contentHash !== route.contentHash || value.release.revision !== route.revision)) throw new Error("Dataset differs from its pinned release."); return value; } });
  const population = useQuery({ queryKey: ["evaluation-workspace", api.key, "releasedDatasetTasks", summary.data?.release.contentHash, afterId], enabled: Boolean(summary.data), queryFn: ({ signal }) => api.request<DatasetPopulationPage>("datasetPopulation", { release: summary.data!.release, view: "policy", limit: 25, ...(afterId ? { afterId } : {}) }, signal) });
  useDatasetTaskSelection(summary.data?.release ?? null);
  const task = population.data?.items.find(item => item.id === taskId);
  const tab = route.detailTab ?? "tasks";
  function inspectTask(id: string) {
    setTaskId(id);
    controls?.select({ id: "task", label: "Task", onSelect: () => {} });
  }
  useWorkspaceActions(task ? [{ id: "task", label: "Task", onSelect: () => {} }] : []);
  useWorkspaceResourceName(summary.data?.name ?? (summary.error ? "Unavailable Dataset" : null));
  return <><header className="evaluation-workspace-header"><h1>{summary.data?.name ?? "Dataset"}</h1></header>{summary.error || population.error ? <p role="alert">{summary.error?.message ?? population.error?.message}</p> : null}{summary.isPending ? <p role="status">Loading released Dataset…</p> : null}{summary.data ? <><p>{summary.data.description}</p><p>Published revision {summary.data.release.revision}, {summary.data.taskCount} tasks</p><nav className="evaluation-workspace-tabs" aria-label="Dataset tabs">{["tasks", "experiments", "graders", "versions"].map(value => <button key={value} aria-selected={tab === value} onClick={() => { setTaskId(null); navigate({ ...route, detailTab: value }); }}>{value[0]!.toUpperCase() + value.slice(1)}</button>)}</nav>
    {tab === "tasks" ? <><DatasetAssignments api={api} release={summary.data.release} route={route} navigate={navigate}/><table className="training-data-table evaluation-workspace-table"><thead><tr><th scope="col"><DatasetTaskSelection release={summary.data.release} count={summary.data.taskCount} route={route} /></th><th>Task</th><th>Input</th><th>Split</th></tr></thead><tbody>{population.data?.items.map(item => <tr key={item.id} tabIndex={0} onClick={() => inspectTask(item.id)} onKeyDown={event => { if (event.key === "Enter") inspectTask(item.id); }}><DatasetTaskCheckbox release={summary.data!.release} id={item.id} route={route} /><td>{item.id}</td><td>{"input" in item ? JSON.stringify(item.input).slice(0, 200) : ""}</td><td>{item.split}</td></tr>)}<EvaluationTableState columns={4} loading={population.isPending} error={population.error?.message} empty={!population.data?.items.length} retry={()=>void population.refetch()}>Use First tasks to return to the beginning of this Dataset version.</EvaluationTableState></tbody></table>{afterId ? <button onClick={() => { setAfter(undefined); setTaskId(null); }}>First tasks</button> : null}{population.data?.nextCursor ? <button onClick={() => { setAfter(population.data!.nextCursor!); setTaskId(null); }}>More tasks</button> : null}</> : tab === "graders" ? <table className="training-data-table"><thead><tr><th>Feedback key</th><th>Version</th><th>Released grader</th></tr></thead><tbody>{population.data?.graders.map(grader => <tr key={grader.id}><td>{grader.feedbackKey}</td><td>{grader.version}</td><td>{grader.release ? <button className="training-text-button" onClick={() => navigate({ ...route, page: "graders", resourceId: grader.release!.id, datasetKind: undefined, revision: grader.release!.revision, contentHash: grader.release!.contentHash, detailTab: "overview" })}>{grader.release.id}, Revision {grader.release.revision}</button> : "Dataset-owned"}</td></tr>)}<EvaluationTableState columns={3} loading={population.isPending} error={population.error?.message} empty={!population.data?.graders.length} retry={()=>void population.refetch()}>Use an authored Dataset with attached Graders to evaluate its outputs.</EvaluationTableState></tbody></table> : tab === "experiments" ? <DatasetExperiments api={api} releaseHash={summary.data.release.contentHash} route={route} navigate={navigate} /> : <dl className="evaluation-workspace-meta"><dt>Release</dt><dd>{summary.data.release.id}, Revision {summary.data.release.revision}</dd><dt>Content hash</dt><dd>{summary.data.release.contentHash}</dd><dt>Package bytes</dt><dd>{summary.data.packageBytes ?? "Unknown"}</dd><dt>Published</dt><dd><EvaluationTime value={summary.data.createdAt} /></dd></dl>}
  </> : null}{task && "input" in task ? <WorkspacePanel action="task" label="Task inspector" onRequestClose={() => setTaskId(null)}><header><h2>{task.id}</h2></header><EvaluationCard title="Input"><pre>{JSON.stringify(task.input, null, 2)}</pre></EvaluationCard><EvaluationCard title="Policy context"><pre>{JSON.stringify(task.policyVisibleContext, null, 2)}</pre></EvaluationCard><EvaluationCard title="Policy artifacts"><pre>{JSON.stringify(task.artifacts, null, 2)}</pre></EvaluationCard></WorkspacePanel> : null}</>;
}
