import {useEffect,useRef,useState} from "react";
import {contentHash} from "@openpond/harness";
import {ExperimentImprovementCommandSchema,verifyExperimentImprovementState,type ExperimentImprovementClient,type ExperimentImprovementCommand,type ExperimentImprovementState} from "openpond-sdk/experiment-improvements";
type Start=Extract<ExperimentImprovementCommand,{operation:"start"}>;
/** The exact scoped original command survives a renderer remount or lost
 * reply. Browser locks protect check/write/clear across concurrent windows. */
export function useRetainedImprovementStart(input:{scope:unknown;actorId:string;teamId:string;projectId:string|null;evidence:{id:string;contentHash:string};client:ExperimentImprovementClient;onRecovered(state:ExperimentImprovementState):void}){
 const key=`openpond:native-improve:start:${contentHash(input.scope)}`,[pending,setPending]=useState<Start|null>(null),[ready,setReady]=useState(false),[error,setError]=useState<string|null>(null),live=useRef(true),generation=useRef(0),recover=useRef(input.onRecovered),hydratedKey=useRef<string|null>(null),currentKey=useRef(key);currentKey.current=key;recover.current=input.onRecovered;
 function parse(text:string){const request=ExperimentImprovementCommandSchema.parse(JSON.parse(text));if(request.operation!=="start"||request.request.projectId!==input.projectId||contentHash(request.request.evidence)!==contentHash(input.evidence))throw new Error("The retained original creation changed its current evidence scope.");return request;}
 async function locked<T>(action:()=>Promise<T>){if(!navigator.locks)throw new Error("Original creation recovery requires the browser's exclusive owner journal lock.");return navigator.locks.request(key,action);}
 async function retain(request:Start){const sequence=generation.current;if(!ready||hydratedKey.current!==key||currentKey.current!==key)throw new Error("Wait for retained creation recovery before starting a candidate.");await locked(async()=>{if(!live.current||currentKey.current!==key||generation.current!==sequence)throw new Error("The original creation account scope changed.");const text=localStorage.getItem(key);if(text&&contentHash(parse(text))!==contentHash(request))throw new Error("Recover the unresolved original creation before starting another candidate.");localStorage.setItem(key,JSON.stringify(request));if(live.current&&currentKey.current===key&&generation.current===sequence)setPending(request);});}
 async function clear(request:Start){const sequence=generation.current;await locked(async()=>{if(!live.current||currentKey.current!==key||generation.current!==sequence)throw new Error("The original creation account scope changed.");const text=localStorage.getItem(key);if(text&&contentHash(parse(text))!==contentHash(request))throw new Error("Another original creation owns this journal.");if(text)localStorage.removeItem(key);if(live.current&&currentKey.current===key&&generation.current===sequence)setPending(null);});}
 useEffect(()=>{live.current=true;const sequence=generation.current,controller=new AbortController();void locked(async()=>{const text=localStorage.getItem(key),request=text?parse(text):null;if(live.current&&generation.current===sequence){hydratedKey.current=key;setPending(request);setReady(true);}return request;}).then(async request=>{if(!request)return;const state=verifyExperimentImprovementState(await input.client.command({operation:"read",id:`improve-${contentHash([input.actorId,input.teamId,request.request.operationId]).slice(0,40)}`},controller.signal));if(state.requestHash!==contentHash(request.request)||state.projectId!==input.projectId||state.evidence.manifest.id!==input.evidence.id||state.evidence.result.contentHash!==input.evidence.contentHash)throw new Error("Original creation readback changed its exact admitted request.");if(live.current&&generation.current===sequence){await clear(request);if(live.current&&generation.current===sequence)recover.current(state);}}).catch(cause=>{if(live.current&&generation.current===sequence){setReady(true);setError(cause instanceof Error?cause.message:String(cause));}});return()=>{live.current=false;generation.current++;controller.abort();};},[key,input.client]);
 return{pending:hydratedKey.current===key?pending:null,ready:ready&&hydratedKey.current===key,error:hydratedKey.current===key?error:null,retain,clear,invalidateRecovery:()=>{generation.current++;}};
}
